# Generated by Django 3.0.14 on 2022-09-26 08:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HedgeFundingProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=75)),
                ('tx_index', models.IntegerField()),
                ('tx_value', models.BigIntegerField()),
                ('script_sig', models.TextField()),
                ('pubkey', models.CharField(default='', max_length=75)),
                ('input_tx_hashes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='HedgePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=75, unique=True)),
                ('anyhedge_contract_version', models.CharField(max_length=20)),
                ('satoshis', models.BigIntegerField()),
                ('start_timestamp', models.DateTimeField()),
                ('maturity_timestamp', models.DateTimeField()),
                ('hedge_wallet_hash', models.CharField(max_length=75)),
                ('hedge_address', models.CharField(max_length=75)),
                ('hedge_pubkey', models.CharField(max_length=75)),
                ('hedge_address_path', models.CharField(blank=True, max_length=10, null=True)),
                ('long_wallet_hash', models.CharField(max_length=75)),
                ('long_address', models.CharField(max_length=75)),
                ('long_pubkey', models.CharField(max_length=75)),
                ('long_address_path', models.CharField(blank=True, max_length=10, null=True)),
                ('oracle_pubkey', models.CharField(max_length=75)),
                ('start_price', models.IntegerField()),
                ('low_liquidation_multiplier', models.FloatField()),
                ('high_liquidation_multiplier', models.FloatField()),
                ('funding_tx_hash', models.CharField(blank=True, max_length=75, null=True)),
                ('funding_tx_hash_validated', models.BooleanField(default=False)),
                ('hedge_funding_proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hedge_position', to='anyhedge.HedgeFundingProposal')),
                ('long_funding_proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_position', to='anyhedge.HedgeFundingProposal')),
            ],
            options={
                'ordering': ['-start_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HedgePositionFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=75)),
                ('funding_output', models.IntegerField()),
                ('funding_satoshis', models.BigIntegerField()),
                ('fee_output', models.IntegerField(blank=True, null=True)),
                ('fee_satoshis', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LongAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_hash', models.CharField(max_length=100, unique=True)),
                ('address_path', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=75)),
                ('pubkey', models.CharField(max_length=75)),
                ('min_auto_accept_duration', models.IntegerField(default=0)),
                ('max_auto_accept_duration', models.IntegerField(default=0)),
                ('auto_accept_allowance', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Oracle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.CharField(max_length=75, unique=True)),
                ('relay', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('asset_name', models.CharField(max_length=25)),
                ('asset_currency', models.CharField(default='', max_length=10)),
                ('asset_decimals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PriceOracleMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.CharField(max_length=75)),
                ('signature', models.CharField(max_length=130)),
                ('message', models.CharField(max_length=40)),
                ('message_timestamp', models.DateTimeField()),
                ('price_value', models.IntegerField()),
                ('price_sequence', models.IntegerField()),
                ('message_sequence', models.IntegerField()),
            ],
            options={
                'ordering': ['-message_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SettlementService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('scheme', models.CharField(max_length=10)),
                ('port', models.IntegerField()),
                ('hedge_signature', models.TextField(blank=True, null=True)),
                ('long_signature', models.TextField(blank=True, null=True)),
                ('hedge_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_service', to='anyhedge.HedgePosition')),
            ],
        ),
        migrations.CreateModel(
            name='MutualRedemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redemption_type', models.CharField(choices=[('refund', 'Refund'), ('early_maturation', 'Early maturation'), ('arbitrary', 'Arbitrary')], max_length=20)),
                ('hedge_satoshis', models.BigIntegerField()),
                ('long_satoshis', models.BigIntegerField()),
                ('hedge_schnorr_sig', models.TextField(blank=True, null=True)),
                ('long_schnorr_sig', models.TextField(blank=True, null=True)),
                ('settlement_price', models.IntegerField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=75, null=True)),
                ('hedge_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_redemption', to='anyhedge.HedgePosition')),
            ],
        ),
        migrations.CreateModel(
            name='HedgeSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spending_transaction', models.CharField(max_length=75)),
                ('settlement_type', models.CharField(max_length=20)),
                ('hedge_satoshis', models.BigIntegerField()),
                ('long_satoshis', models.BigIntegerField()),
                ('oracle_pubkey', models.CharField(max_length=75)),
                ('settlement_price', models.IntegerField(blank=True, null=True)),
                ('settlement_price_sequence', models.IntegerField(blank=True, null=True)),
                ('settlement_message_sequence', models.IntegerField(blank=True, null=True)),
                ('settlement_message_timestamp', models.DateTimeField(blank=True, null=True)),
                ('settlement_message', models.CharField(blank=True, max_length=40, null=True)),
                ('settlement_signature', models.CharField(blank=True, max_length=130, null=True)),
                ('hedge_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='anyhedge.HedgePosition')),
            ],
        ),
        migrations.CreateModel(
            name='HedgePositionOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('wallet_hash', models.CharField(max_length=100)),
                ('satoshis', models.BigIntegerField()),
                ('duration_seconds', models.IntegerField()),
                ('high_liquidation_multiplier', models.FloatField()),
                ('low_liquidation_multiplier', models.FloatField()),
                ('oracle_pubkey', models.CharField(blank=True, max_length=75, null=True)),
                ('hedge_address', models.CharField(max_length=75)),
                ('hedge_pubkey', models.CharField(max_length=75)),
                ('hedge_address_path', models.CharField(blank=True, max_length=10, null=True)),
                ('auto_settled', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hedge_position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_offer', to='anyhedge.HedgePosition')),
            ],
        ),
        migrations.CreateModel(
            name='HedgePositionFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=75)),
                ('satoshis', models.IntegerField()),
                ('hedge_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='anyhedge.HedgePosition')),
            ],
        ),
    ]
