# Generated by Django 3.0.14 on 2022-09-07 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HedgeFundingProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=75)),
                ('tx_index', models.IntegerField()),
                ('tx_value', models.BigIntegerField()),
                ('script_sig', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HedgePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=75, unique=True)),
                ('anyhedge_contract_version', models.CharField(max_length=20)),
                ('satoshis', models.BigIntegerField()),
                ('start_timestamp', models.DateTimeField()),
                ('maturity_timestamp', models.DateTimeField()),
                ('hedge_wallet_hash', models.CharField(max_length=75)),
                ('hedge_address', models.CharField(max_length=75)),
                ('hedge_pubkey', models.CharField(max_length=75)),
                ('long_wallet_hash', models.CharField(max_length=75)),
                ('long_address', models.CharField(max_length=75)),
                ('long_pubkey', models.CharField(max_length=75)),
                ('oracle_pubkey', models.CharField(max_length=75)),
                ('start_price', models.IntegerField()),
                ('low_liquidation_multiplier', models.FloatField()),
                ('high_liquidation_multiplier', models.FloatField()),
                ('funding_tx_hash', models.CharField(blank=True, max_length=75, null=True)),
                ('hedge_funding_proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hedge_position', to='anyhedge.HedgeFundingProposal')),
                ('long_funding_proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_position', to='anyhedge.HedgeFundingProposal')),
            ],
        ),
        migrations.CreateModel(
            name='LongAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_hash', models.CharField(max_length=100, unique=True)),
                ('address_path', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=75)),
                ('pubkey', models.CharField(max_length=75)),
                ('min_auto_accept_duration', models.IntegerField(default=0)),
                ('max_auto_accept_duration', models.IntegerField(default=0)),
                ('auto_accept_allowance', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HedgePositionOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('wallet_hash', models.CharField(max_length=100)),
                ('satoshis', models.BigIntegerField()),
                ('duration_seconds', models.IntegerField()),
                ('high_liquidation_multiplier', models.FloatField()),
                ('low_liquidation_multiplier', models.FloatField()),
                ('hedge_address', models.CharField(max_length=75)),
                ('hedge_pubkey', models.CharField(max_length=75)),
                ('auto_settled', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hedge_position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_offer', to='anyhedge.HedgePosition')),
            ],
        ),
    ]
