# Generated by Django 3.0.14 on 2022-10-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hedgeposition',
            name='address',
            field=models.CharField(db_index=True, max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='hedgeposition',
            name='funding_tx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='hedgeposition',
            name='hedge_wallet_hash',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='hedgeposition',
            name='long_wallet_hash',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='hedgepositionfunding',
            name='tx_hash',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='hedgepositionoffer',
            name='wallet_hash',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hedgesettlement',
            name='spending_transaction',
            field=models.CharField(db_index=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='longaccount',
            name='wallet_hash',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='oracle',
            name='asset_name',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='priceoraclemessage',
            name='message_sequence',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='priceoraclemessage',
            name='message_timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='priceoraclemessage',
            name='price_sequence',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='priceoraclemessage',
            name='pubkey',
            field=models.CharField(db_index=True, max_length=75),
        ),
    ]
