# Generated by Django 3.0.14 on 2022-09-07 08:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgefundingproposal',
            name='input_tx_hashes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='hedgefundingproposal',
            name='pubkey',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='hedgepositionoffer',
            name='hedge_funding_proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hedge_position_offer', to='anyhedge.HedgeFundingProposal'),
        ),
    ]
