# Generated by Django 3.0.14 on 2022-11-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0002_auto_20221025_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementservice',
            name='auth_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
