# Generated by Django 3.0.14 on 2022-09-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0002_auto_20220907_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oracle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.CharField(max_length=75, unique=True)),
                ('relay', models.CharField(max_length=50)),
                ('port', models.IntegerField()),
                ('asset_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PriceOracleMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey', models.CharField(max_length=75)),
                ('signature', models.CharField(max_length=130)),
                ('message', models.CharField(max_length=40)),
                ('message_timestamp', models.DateTimeField()),
                ('price_value', models.IntegerField()),
                ('price_sequence', models.IntegerField()),
                ('message_sequence', models.IntegerField()),
            ],
        ),
    ]
