# Generated by Django 3.0.14 on 2022-11-09 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0003_settlementservice_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='HedgePositionMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_taker', models.CharField(blank=True, choices=[('hedge', 'hedge'), ('long', 'long')], max_length=5, null=True)),
                ('liquidity_fee', models.IntegerField(blank=True, null=True)),
                ('network_fee', models.IntegerField(blank=True, null=True)),
                ('total_hedge_funding_sats', models.IntegerField(blank=True, null=True)),
                ('total_long_funding_sats', models.IntegerField(blank=True, null=True)),
                ('hedge_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='anyhedge.HedgePosition')),
            ],
        ),
    ]
