# Generated by Django 3.0.14 on 2022-09-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0003_oracle_priceoraclemessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceoraclemessage',
            options={'ordering': ['-message_timestamp']},
        ),
        migrations.AddField(
            model_name='hedgepositionoffer',
            name='oracle_pubkey',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
