# Generated by Django 3.0.14 on 2023-01-06 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0004_hedgepositionmetadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hedgepositionoffer',
            old_name='hedge_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hedgepositionoffer',
            old_name='hedge_pubkey',
            new_name='pubkey',
        ),
        migrations.RemoveField(
            model_name='hedgepositionoffer',
            name='auto_settled',
        ),
        migrations.RemoveField(
            model_name='hedgepositionoffer',
            name='hedge_address_path',
        ),
        migrations.AddField(
            model_name='hedgepositionoffer',
            name='address_path',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='hedgepositionoffer',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hedgepositionoffer',
            name='position',
            field=models.CharField(blank=True, choices=[('hedge', 'Hedge'), ('long', 'Long')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='hedgepositionoffer',
            name='oracle_pubkey',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='hedgepositionoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='HedgePositionOfferCounterParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(db_index=True, max_length=75, unique=True)),
                ('anyhedge_contract_version', models.CharField(max_length=20)),
                ('wallet_hash', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=75)),
                ('pubkey', models.CharField(max_length=75)),
                ('address_path', models.CharField(max_length=10)),
                ('price_message_timestamp', models.DateTimeField()),
                ('price_value', models.IntegerField()),
                ('oracle_message_sequence', models.IntegerField()),
                ('settlement_deadline', models.DateTimeField(blank=True, null=True)),
                ('hedge_position_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter_party_info', to='anyhedge.HedgePositionOffer')),
            ],
        ),
    ]
