# Generated by Django 3.0.14 on 2022-09-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0004_auto_20220909_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='oracle',
            name='asset_currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='oracle',
            name='asset_decimals',
            field=models.IntegerField(default=0),
        ),
    ]
