# Generated by Django 3.0.14 on 2022-09-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0005_auto_20220910_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hedgepositionoffer',
            name='hedge_funding_proposal',
        ),
    ]
