# Generated by Django 3.2.16 on 2023-01-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0005_auto_20230106_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgepositionoffercounterparty',
            name='settlement_service_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hedgepositionoffercounterparty',
            name='settlement_service_fee_address',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AlterField(
            model_name='hedgepositionoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('settled', 'Settled')], default='pending', max_length=15),
        ),
    ]
