# Generated by Django 3.0.14 on 2022-09-14 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0006_remove_hedgepositionoffer_hedge_funding_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('scheme', models.CharField(max_length=10)),
                ('port', models.IntegerField()),
                ('hedge_signature', models.TextField()),
                ('hedge_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_service', to='anyhedge.HedgePosition')),
            ],
        ),
        migrations.CreateModel(
            name='HedgePositionFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=75)),
                ('satoshis', models.IntegerField()),
                ('hedge_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='anyhedge.HedgePosition')),
            ],
        ),
    ]
