# Generated by Django 3.2.16 on 2023-01-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0006_auto_20230109_0049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LongAccount',
        ),
    ]
