# Generated by Django 3.0.14 on 2022-09-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0007_hedgepositionfee_settlementservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hedgeposition',
            options={'ordering': ['-start_timestamp']},
        ),
        migrations.CreateModel(
            name='HedgeSettlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spending_transaction', models.CharField(max_length=75)),
                ('settlement_type', models.CharField(max_length=20)),
                ('hedge_satoshis', models.BigIntegerField()),
                ('long_satoshis', models.BigIntegerField()),
                ('oracle_pubkey', models.CharField(max_length=75)),
                ('settlement_price', models.IntegerField(blank=True, null=True)),
                ('settlement_price_sequence', models.IntegerField(blank=True, null=True)),
                ('settlement_message_sequence', models.IntegerField(blank=True, null=True)),
                ('settlement_message_timestamp', models.DateTimeField(blank=True, null=True)),
                ('settlement_message', models.CharField(blank=True, max_length=40, null=True)),
                ('settlement_signature', models.CharField(blank=True, max_length=130, null=True)),
                ('hedge_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='anyhedge.HedgePosition')),
            ],
        ),
    ]
