# Generated by Django 3.0.14 on 2023-01-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0008_mutualredemption_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgeposition',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hedgeposition',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
