# Generated by Django 3.0.14 on 2022-09-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0008_auto_20220915_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='HedgePositionFunding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=75)),
                ('funding_output', models.IntegerField()),
                ('funding_satoshis', models.BigIntegerField()),
                ('fee_output', models.IntegerField(blank=True, null=True)),
                ('fee_satoshis', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hedgeposition',
            name='funding_tx_hash_validated',
            field=models.BooleanField(default=False),
        ),
    ]
