# Generated by Django 3.0.14 on 2023-01-31 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0009_auto_20230127_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hedgepositionfunding',
            name='fee_output',
        ),
        migrations.RemoveField(
            model_name='hedgepositionfunding',
            name='fee_satoshis',
        ),
        migrations.AddField(
            model_name='hedgeposition',
            name='starting_oracle_message',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hedgeposition',
            name='starting_oracle_signature',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hedgepositionfee',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hedgepositionfee',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hedgepositionfunding',
            name='hedge_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='anyhedge.HedgePosition'),
        ),
        migrations.AddField(
            model_name='hedgepositionfunding',
            name='settlement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding', to='anyhedge.HedgeSettlement'),
        ),
        migrations.AddField(
            model_name='hedgepositionfunding',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hedgepositionoffercounterparty',
            name='starting_oracle_message',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hedgepositionoffercounterparty',
            name='starting_oracle_signature',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutualredemption',
            name='funding_tx_hash',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='hedgepositionfee',
            name='hedge_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='anyhedge.HedgePosition'),
        ),
        migrations.AlterField(
            model_name='hedgepositionfunding',
            name='funding_output',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='hedgepositionfunding',
            name='funding_satoshis',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='hedgesettlement',
            name='hedge_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='anyhedge.HedgePosition'),
        ),
    ]
