# Generated by Django 3.0.14 on 2022-09-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0009_auto_20220920_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgeposition',
            name='hedge_address_path',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hedgeposition',
            name='long_address_path',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hedgepositionoffer',
            name='hedge_address_path',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
