# Generated by Django 3.0.14 on 2023-02-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0010_auto_20230131_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hedgepositionfee',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hedgepositionfee',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
