# Generated by Django 3.0.14 on 2022-09-23 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0010_auto_20220922_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualRedemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redemption_type', models.CharField(choices=[('refund', 'Refund'), ('early_maturation', 'Early maturation'), ('arbitrary', 'Arbitrary')], max_length=20)),
                ('hedge_satoshis', models.BigIntegerField()),
                ('long_satoshis', models.BigIntegerField()),
                ('hedge_schnorr_sig', models.TextField(blank=True, null=True)),
                ('long_schnorr_sig', models.TextField(blank=True, null=True)),
                ('settlement_price', models.IntegerField(blank=True, null=True)),
                ('tx_hash', models.CharField(blank=True, max_length=75, null=True)),
                ('hedge_position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_redemption', to='anyhedge.HedgePosition')),
            ],
        ),
    ]
