# Generated by Django 3.0.14 on 2022-09-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0011_mutualredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementservice',
            name='long_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settlementservice',
            name='hedge_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
