# Generated by Django 3.0.14 on 2023-05-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0011_auto_20230201_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='oracle',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
