# Generated by Django 3.0.14 on 2024-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyhedge', '0013_auto_20240413_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedgeposition',
            name='is_simple_hedge',
            field=models.BooleanField(default=True),
        ),
    ]
