from main.views.view_home import *
from main.views.view_slp import *
from main.views.view_token import *
from main.views.view_transaction import *
from main.views.view_user_auth import *
from main.views.view_telegram import *
from main.views.view_subscribe import *
from main.views.view_test import *
from main.views.view_balance import *
from main.views.view_utxo import *
from main.views.view_broadcast import *
from main.views.view_blockheight import *
