from main.views.view_account import *
from main.views.view_address import *
from main.views.view_auth import *
from main.views.view_home import *
from main.views.view_slp import *
from main.views.view_token import *
from main.views.view_subscription import *
from main.views.view_transaction import *
from main.views.view_telegram import *