from main.views.view_address_scan import *
from main.views.view_telegram import *
from main.views.view_subscribe import *
from main.views.view_test import *
from main.views.view_balance import *
from main.views.view_utxo import *
from main.views.view_broadcast import *
from main.views.view_blockheight import *
from main.views.view_history import *
from main.views.view_tokens import *
from main.views.view_tasks import *
from main.views.view_transaction import *
from main.views.view_wallet_preferences import *
from main.views.view_paymentrequest import *
from main.views.view_cashtokens import *
from main.views.view_webhook import *
