from rest_framework import (
    status,
    viewsets,
)
from rest_framework.decorators import action
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from django.db.models import Q, F, Value
from django.db.models.functions import Substr, Cast
from django.db.models.fields import BigIntegerField

from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi

from main.utils.subscription import new_subscription
from main.models import Address, Wallet
from main import serializers

import logging

LOGGER = logging.getLogger(__name__)


class AdvanceSubscriptionViewSet(viewsets.GenericViewSet):
    serializer_class = serializers.AdvanceSubscriptionSerializer
    permission_classes = [AllowAny,]

    @swagger_auto_schema(responses={200: serializers.AdvanceSubscriptionResponseSerializer()})
    def create(self, request, *args, **kwargs):
        """
        Advance subscribe up to 50 address pairs (100 addresses total).
        
        This endpoint is used by Paytaca when connecting to WizardConnect dapps
        to proactively subscribe to addresses that may be generated by dapps
        before Paytaca can track them.
        
        Request format:
        {
            "wallet_hash": "abc123",
            "start_index": 5,
            "address_pairs": [
                {
                    "receiving": "bitcoincash:qr...",
                    "change": "bitcoincash:qp..."
                },
                ...  // up to 50 pairs
            ]
        }
        
        - Validates maximum 50 address pairs
        - Address pairs are sequential starting from start_index
        - Skips addresses that already exist with advance_subscription=False
        - Creates new addresses with advance_subscription=True
        - Triggers immediate UTXO scans for each address
        
        Returns summary of subscribed and skipped addresses.
        """
        serializer = self.get_serializer(data=request.data)

        if not serializer.is_valid():
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        wallet_hash = serializer.validated_data["wallet_hash"]
        project_id = serializer.validated_data.get("project_id", None)
        start_index = serializer.validated_data["start_index"]
        address_pairs = serializer.validated_data["address_pairs"]

        subscribed_count = 0
        skipped_count = 0

        for i, pair in enumerate(address_pairs):
            address_index = start_index + i
            receiving_addr = pair["receiving"]
            change_addr = pair["change"]

            # Check if addresses already exist with advance_subscription=False
            receiving_obj = Address.objects.filter(address=receiving_addr).first()
            receiving_is_regular = receiving_obj and receiving_obj.advance_subscription == False

            change_obj = Address.objects.filter(address=change_addr).first()
            change_is_regular = change_obj and change_obj.advance_subscription == False

            # Skip if either address already exists as regular subscription
            if receiving_is_regular or change_is_regular:
                LOGGER.info(
                    f"Skipping advance subscription for index {address_index}: "
                    f"receiving={receiving_is_regular}, change={change_is_regular}"
                )
                skipped_count += 2  # Both addresses in the pair
                continue

            # Subscribe the address pair
            try:
                result = new_subscription(
                    wallet_hash=wallet_hash,
                    project_id=project_id,
                    address_index=address_index,
                    addresses={
                        "receiving": receiving_addr,
                        "change": change_addr
                    },
                    advance_subscription=True
                )

                if result.get("success"):
                    subscribed_count += 2  # Both addresses in the pair
                    LOGGER.info(f"Advance subscribed addresses for index {address_index}")
                else:
                    error_msg = result.get("error", "Unknown error")
                    LOGGER.error(f"Failed to advance subscribe index {address_index}: {error_msg}")
                    skipped_count += 2

            except Exception as e:
                LOGGER.error(f"Error advance subscribing index {address_index}: {str(e)}")
                skipped_count += 2

        response_data = {
            "subscribed": subscribed_count,
            "skipped": skipped_count,
            "start_index": start_index,
            "end_index": start_index + len(address_pairs) - 1
        }

        return Response(response_data, status=status.HTTP_200_OK)
    
    @action(detail=False, methods=['get'], url_path='count')
    @swagger_auto_schema(
        manual_parameters=[
            openapi.Parameter(
                name="wallet_hash",
                type=openapi.TYPE_STRING,
                in_=openapi.IN_QUERY,
                required=True,
                description="Wallet hash to check advance subscriptions for"
            ),
            openapi.Parameter(
                name="exclude_pos",
                type=openapi.TYPE_BOOLEAN,
                in_=openapi.IN_QUERY,
                default=False,
                description="Exclude POS addresses from count"
            ),
        ],
        responses={
            200: openapi.Response(
                description="Count of advance subscribed addresses",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        'wallet_hash': openapi.Schema(type=openapi.TYPE_STRING),
                        'total_advance_subscribed': openapi.Schema(type=openapi.TYPE_INTEGER, description='Total addresses with advance_subscription=True'),
                        'receiving_advance_subscribed': openapi.Schema(type=openapi.TYPE_INTEGER, description='Receiving addresses (0/X) with advance_subscription=True'),
                        'change_advance_subscribed': openapi.Schema(type=openapi.TYPE_INTEGER, description='Change addresses (1/X) with advance_subscription=True'),
                        'pairs_advance_subscribed': openapi.Schema(type=openapi.TYPE_INTEGER, description='Number of complete pairs (both receiving and change) with advance_subscription=True'),
                    }
                )
            ),
            400: "Bad request - wallet_hash is required",
            404: "Wallet not found"
        }
    )
    def count(self, request):
        """
        Get count of advance subscribed addresses for a wallet.
        
        Returns:
        - total_advance_subscribed: Total count of addresses with advance_subscription=True
        - receiving_advance_subscribed: Count of receiving addresses (0/X)
        - change_advance_subscribed: Count of change addresses (1/X)
        - pairs_advance_subscribed: Count of indices where BOTH receiving and change are advance subscribed
        
        This helps the Paytaca app determine if it needs to top up the advance subscription buffer.
        """
        wallet_hash = request.query_params.get("wallet_hash")
        exclude_pos = request.query_params.get("exclude_pos", False)
        
        if not wallet_hash:
            return Response(
                {"error": "wallet_hash query parameter is required"},
                status=status.HTTP_400_BAD_REQUEST
            )
        
        # Check if wallet exists
        try:
            wallet = Wallet.objects.get(wallet_hash=wallet_hash)
        except Wallet.DoesNotExist:
            return Response(
                {"error": f"Wallet with hash {wallet_hash} not found"},
                status=status.HTTP_404_NOT_FOUND
            )
        
        # Convert string to boolean
        if isinstance(exclude_pos, str) and exclude_pos.lower() == "false":
            exclude_pos = False
        
        # Base queryset for advance subscribed addresses
        base_queryset = Address.objects.filter(
            wallet=wallet,
            advance_subscription=True,
        )
        
        # Get receiving addresses (0/X)
        receiving_qs = base_queryset.filter(
            address_path__startswith='0/'
        ).annotate(
            address_index=Cast(
                Substr(F("address_path"), Value("0/(\\d+)")), BigIntegerField()
            )
        ).filter(
            address_index__isnull=False
        )
        
        # Get change addresses (1/X)
        change_qs = base_queryset.filter(
            address_path__startswith='1/'
        ).annotate(
            address_index=Cast(
                Substr(F("address_path"), Value("1/(\\d+)")), BigIntegerField()
            )
        ).filter(
            address_index__isnull=False
        )
        
        # Apply POS exclusion if needed
        if exclude_pos:
            from main.views.view_history import POS_ID_MAX_DIGITS
            POSID_MULTIPLIER = 10**POS_ID_MAX_DIGITS
            MAX_UNHARDENED_ADDRESS_INDEX = 2**32 - 1
            
            receiving_qs = receiving_qs.exclude(
                address_index__gte=POSID_MULTIPLIER,
                address_index__lte=MAX_UNHARDENED_ADDRESS_INDEX,
            )
            change_qs = change_qs.exclude(
                address_index__gte=POSID_MULTIPLIER,
                address_index__lte=MAX_UNHARDENED_ADDRESS_INDEX,
            )
        
        # Get counts
        receiving_count = receiving_qs.count()
        change_count = change_qs.count()
        
        # Get indices for each type to find complete pairs
        receiving_indices = set(receiving_qs.values_list('address_index', flat=True))
        change_indices = set(change_qs.values_list('address_index', flat=True))
        
        # Count complete pairs (indices where BOTH receiving AND change are advance subscribed)
        complete_pairs = len(receiving_indices & change_indices)
        
        data = {
            "wallet_hash": wallet_hash,
            "total_advance_subscribed": receiving_count + change_count,
            "receiving_advance_subscribed": receiving_count,
            "change_advance_subscribed": change_count,
            "pairs_advance_subscribed": complete_pairs,
        }
        
        return Response(data, status=status.HTTP_200_OK)
