# Generated by Django 3.0.14 on 2024-09-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stablehedge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptioncontracttransaction',
            name='wallet_hash',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='redemptioncontracttransaction',
            name='result_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
