# Generated by Django 3.0.14 on 2024-10-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stablehedge', '0002_auto_20240925_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70)),
                ('auth_token_id', models.CharField(max_length=64)),
                ('pubkey1', models.CharField(max_length=70)),
                ('pubkey2', models.CharField(max_length=70)),
                ('pubkey3', models.CharField(max_length=70)),
                ('pubkey4', models.CharField(max_length=70)),
                ('pubkey5', models.CharField(max_length=70)),
            ],
        ),
    ]
