# Generated by Django 3.0.14 on 2024-12-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stablehedge', '0004_treasurycontract_encrypted_funding_wif'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryContractKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubkey1_wif', models.CharField(blank=True, help_text="Add prefix 'bch-wif:', if data is not encrypted", max_length=200, null=True)),
                ('pubkey2_wif', models.CharField(blank=True, help_text="Add prefix 'bch-wif:', if data is not encrypted", max_length=200, null=True)),
                ('pubkey3_wif', models.CharField(blank=True, help_text="Add prefix 'bch-wif:', if data is not encrypted", max_length=200, null=True)),
                ('pubkey4_wif', models.CharField(blank=True, help_text="Add prefix 'bch-wif:', if data is not encrypted", max_length=200, null=True)),
                ('pubkey5_wif', models.CharField(blank=True, help_text="Add prefix 'bch-wif:', if data is not encrypted", max_length=200, null=True)),
                ('treasury_contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stablehedge.TreasuryContract')),
            ],
        ),
    ]
