# Generated by Django 3.0.14 on 2024-12-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stablehedge', '0005_treasurycontractkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptioncontract',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
