# Generated by Django 3.0.14 on 2025-01-06 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stablehedge', '0006_redemptioncontract_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryContractShortPositionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_satoshis', models.BigIntegerField(default=100000000, help_text='Short all funds when treasury contract balance reach this value')),
                ('treasury_contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_position_rule', to='stablehedge.TreasuryContract')),
            ],
        ),
    ]
