# Generated by Django 3.0.14 on 2025-03-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stablehedge', '0008_auto_20250108_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurycontract',
            name='anyhedge_base_bytecode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treasurycontract',
            name='anyhedge_contract_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treasurycontract',
            name='version',
            field=models.CharField(choices=[('v1', 'V1'), ('v2', 'V2')], default='v1', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treasurycontract',
            name='pubkey4',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='treasurycontract',
            name='pubkey5',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
