# Generated by Django 3.0.14 on 2025-05-30 01:55

from django.db import migrations, models
import django.db.models.deletion


def populate_redemption_contract(apps, schema_editor):
    RedemptionContract = apps.get_model("stablehedge", "RedemptionContract")
    TreasuryContract = apps.get_model("stablehedge", "TreasuryContract")

    subq = TreasuryContract.objects.filter(redemption_contract_id=models.OuterRef("pk")) \
        .values("pk")[:1]

    RedemptionContract.objects.update(treasury_contract_id=subq)

def populate_treasury_contract(apps, schema_editor):
    RedemptionContract = apps.get_model("stablehedge", "RedemptionContract")
    TreasuryContract = apps.get_model("stablehedge", "TreasuryContract")

    subq = RedemptionContract.objects.filter(treasury_contract_id=models.OuterRef("pk")) \
        .values("pk")[:1]

    TreasuryContract.objects.update(redemption_contract_id=subq)


class Migration(migrations.Migration):

    dependencies = [
        ('stablehedge', '0009_auto_20250318_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurycontract',
            name='redemption_contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_contract', to='stablehedge.RedemptionContract'),
        ),
        migrations.AddField(
            model_name='redemptioncontract',
            name='treasury_contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redemption_contract', to='stablehedge.TreasuryContract'),
        ),
        migrations.RunPython(populate_redemption_contract, populate_treasury_contract),
        migrations.RemoveField(
            model_name='TreasuryContract',
            name='redemption_contract',
        ),


        migrations.AlterField(
            model_name='treasurycontract',
            name='version',
            field=models.CharField(choices=[('v1', 'V1'), ('v2', 'V2'), ('v3', 'V3')], max_length=5),
        ),
        migrations.AddField(
            model_name='redemptioncontract',
            name='version',
            field=models.CharField(choices=[('v1', 'V1'), ('v2', 'V2')], default='v1', max_length=5),
            preserve_default=False,
        ),


        migrations.AddField(
            model_name='treasurycontract',
            name='fiat_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treasury_contracts', to='stablehedge.FiatToken'),
        ),
        migrations.AddField(
            model_name='treasurycontract',
            name='price_oracle_pubkey',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='treasurycontract',
            name='redemption_contract_base_bytecode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treasurycontract',
            name='redemption_contract_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
