# Generated by Django 3.0.14 on 2025-06-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stablehedge', '0010_MANUAL_reverse_contracts_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurycontract',
            name='version',
            field=models.CharField(choices=[('v1', 'V1'), ('v2', 'V2')], max_length=5),
        ),
    ]
