# Generated by Django 3.0.14 on 2025-10-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stablehedge', '0011_auto_20250627_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptioncontracttransaction',
            name='fee_sats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
