# Generated by Django 3.0.14 on 2025-10-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stablehedge', '0011_auto_20250627_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptioncontracttransaction',
            name='fee_sats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='redemptioncontract',
            name='version',
            field=models.CharField(choices=[('v1', 'V1'), ('v2', 'V2'), ('v3', 'V3')], max_length=5),
        ),
        migrations.CreateModel(
            name='RedemptionContractOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_fee_amount', models.DecimalField(decimal_places=4, default=0, help_text='If fixed type, must be greater than 1. If percentage type, must be less than 1', max_digits=12)),
                ('redeem_fee_amount', models.DecimalField(decimal_places=4, default=0, help_text='If fixed type, must be greater than 1. If percentage type, must be less than 1', max_digits=12)),
                ('redemption_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='stablehedge.RedemptionContract')),
            ],
        ),
    ]
