# Generated by Django 3.0.14 on 2025-10-27 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stablehedge', '0012_auto_20251008_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurycontractshortpositionrule',
            name='minimum_interval',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Field format DD HH:mm:ss. Set a duration since last short maturity or deposit to short again, even if target satoshis is not met'),
        ),
    ]
