import inspect
import traceback
import logging
from functools import wraps

LOGGER = logging.getLogger(__name__)

def get_stack_frames(start=0, end=10):
    stack = []
    for i, (frame, lineno) in enumerate(traceback.walk_stack(None)):
        if start <= i < end:
            stack.append(inspect.getframeinfo(frame))

        if i >= end: break

    return stack

def get_stack_frame(index=0):
    return get_stack_frames(start=index, end=index+1)[0]

def format_stack_frame(frame):
    return f"{frame.filename}:{frame.lineno} in {frame.function}"

def log_signal_activity(signal_name=None):
    """
    Decorator to log which part of the code triggered a Django signal receiver.
    Generated by ChatGPT.
    """
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            # Skip the first few frames (signal machinery)
            # You can tune how deep you go depending on the context
            trigger_info = format_stack_frame(get_stack_frame(6))

            LOGGER.info(
                f"Signal '{signal_name or func.__name__}' handled by {func.__module__}.{func.__name__}, "
                f"triggered from {trigger_info}"
            )

            return func(*args, **kwargs)
        return wrapper
    return decorator
