# Generated by Django 3.0.14 on 2025-08-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='instructions',
            new_name='note',
        ),
        migrations.AddField(
            model_name='memo',
            name='txid',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
