# Generated by Django 3.0.14 on 2025-08-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_auto_20250811_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='wallet_hash',
            field=models.CharField(db_index=True, max_length=75),
        ),
    ]
