# Generated by Django 3.0.14 on 2025-09-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0003_auto_20250814_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='txid',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
