# Generated by Django 3.0.14 on 2023-07-07 09:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('limit_per_wallet', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('wallet_hash', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gift_code_hash', models.CharField(db_index=True, max_length=70, unique=True)),
                ('address', models.CharField(max_length=64)),
                ('amount', models.FloatField(default=0)),
                ('share', models.CharField(max_length=255)),
                ('date_funded', models.DateTimeField(null=True)),
                ('date_claimed', models.DateTimeField(null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='paytacagifts.Campaign')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='paytacagifts.Wallet')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='paytacagifts.Wallet'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='paytacagifts.Campaign')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='paytacagifts.Gift')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='paytacagifts.Wallet')),
            ],
            options={
                'unique_together': {('wallet', 'gift')},
            },
        ),
    ]
