# Generated by Django 3.0.14 on 2023-07-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytacagifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='paytacagifts.Campaign'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='date_claimed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='date_funded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
