# Generated by Django 3.0.14 on 2024-04-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacagifts', '0003_auto_20230719_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='succeeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gift',
            name='claim_txid',
            field=models.CharField(blank=True, db_index=True, max_length=70),
        ),
    ]
