# Generated by Django 3.0.14 on 2024-09-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacagifts', '0006_gift_encrypted_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='encrypted_share',
            field=models.TextField(default=''),
        ),
    ]
