from enum import Enum

class ViewCode(Enum):
    PEER_CREATE = 'PEER_CREATE'
    PEER_UPDATE = 'PEER_UPDATE'
    PAYMENT_METHOD_LIST = 'PAYMENT_METHOD_LIST'
    PAYMENT_METHOD_CREATE = 'PAYMENT_METHOD_CREATE'
    PAYMENT_METHOD_GET = 'PAYMENT_METHOD_GET'
    PAYMENT_METHOD_UPDATE = 'PAYMENT_METHOD_UPDATE'
    PAYMENT_METHOD_DELETE = 'PAYMENT_METHOD_DELETE'

    ORDER_LIST = 'ORDER_LIST'
    ORDER_CREATE = 'ORDER_CREATE'
    ORDER_CANCEL = 'ORDER_CANCEL'
    ORDER_CONFIRM = 'ORDER_CONFIRM'
    ORDER_ESCROW_PENDING = 'ORDER_ESCROW_PENDING'
    ORDER_ESCROW_VERIFY = 'ORDER_ESCROW_VERIFY'
    ORDER_BUYER_CONF_PAYMENT = 'ORDER_BUYER_CONF_PAYMENT'
    ORDER_SELLER_CONF_PAYMENT = 'ORDER_SELLER_CONF_PAYMENT'
    
    APPEAL_REQUEST = 'APPEAL_REQUEST'
    APPEAL_PENDING_RELEASE = 'APPEAL_PENDING_RELEASE'
    APPEAL_PENDING_REFUND = 'APPEAL_PENDING_REFUND'
    
    CONTRACT_CREATE = 'CONTRACT_CREATE'

    AD_CREATE = 'AD_CREATE'
    AD_UPDATE = 'AD_UPDATE'
    AD_DELETE = 'AD_DELETE'
    AD_LIST = 'AD_LIST'
    AD_GET = 'AD_GET'

    FEEDBACK_ARBITER_CREATE = 'FEEDBACK_ARBITER_CREATE'
    FEEDBACK_PEER_CREATE = 'FEEDBACK_PEER_CREATE'
