from enum import Enum

class ViewCode(Enum):
    PUT_PEER = 'PUT_PEER'
    POST_PEER = 'POST_PEER'
    LIST_PAYMENT_METHOD = 'LIST_PAYMENT_METHOD'
    POST_PAYMENT_METHOD = 'POST_PAYMENT_METHOD'
    GET_PAYMENT_METHOD = 'GET_PAYMENT_METHOD'
    PUT_PAYMENT_METHOD = 'PUT_PAYMENT_METHOD'
    DEL_PAYMENT_METHOD = 'DEL_PAYMENT_METHOD'

    ORDER_CREATE = 'ORDER_CREATE'
    ORDER_CANCEL = 'ORDER_CANCEL'
    ORDER_CONFIRM = 'ORDER_CONFIRM'
    ORDER_BUYER_CONF_PAYMENT = 'ORDER_BUYER_CONF_PAYMENT'
    ORDER_SELLER_CONF_PAYMENT = 'ORDER_SELLER_CONF_PAYMENT'
    ORDER_RELEASE = 'ORDER_RELEASE'
    ORDER_REFUND = 'ORDER_REFUND'

    AD_CREATE = 'AD_CREATE'
    AD_UPDATE = 'AD_UPDATE'
    AD_DELETE = 'AD_DELETE'

    APPEAL_CANCEL = 'APPEAL_CANCEL'
    APPEAL_RELEASE = 'APPEAL_RELEASE'
    APPEAL_REFUND = 'APPEAL_REFUND'
