# Generated by Django 3.0.14 on 2023-01-18 06:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('required_fee_per_byte', models.FloatField(default=1.1)),
                ('memo', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
                ('merchant_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=70)),
                ('memo', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField()),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='jpp.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePaymentRefundOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('address', models.CharField(max_length=70)),
                ('invoice_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_to', to='jpp.InvoicePayment')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('address', models.CharField(max_length=70)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='jpp.Invoice')),
            ],
        ),
    ]
