# Generated by Django 3.0.14 on 2025-08-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceoutput',
            name='capability',
            field=models.CharField(blank=True, choices=[('mutable', 'Mutable'), ('none', 'None'), ('minting', 'Minting')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceoutput',
            name='category',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='invoiceoutput',
            name='commitment',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='invoiceoutput',
            name='token_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
