# Generated by Django 3.0.14 on 2025-12-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpp', '0002_auto_20250826_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceoutput',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
