# Generated by Django 3.0.14 on 2025-04-16 07:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultisigWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m', models.IntegerField()),
                ('n', models.IntegerField()),
                ('template', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpub', models.CharField(max_length=120)),
                ('derivation_path', models.CharField(default="m/44'/145'/0'/0/0", max_length=120)),
            ],
            options={
                'unique_together': {('xpub', 'derivation_path')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(blank=True, max_length=64, null=True)),
                ('unsigned_hex', models.TextField(unique=True)),
                ('unsigned_hex_hash', models.TextField(help_text='Sha256 hash of the unsigned hex', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignerTransactionSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_index', models.IntegerField()),
                ('signature', models.CharField(help_text='Hex-encoded signature', max_length=200)),
                ('signature_algo', models.CharField(choices=[('ecdsa', 'ecdsa'), ('schnorr', 'schnorr')], default='schnorr', help_text='Signature algorithm used (ecdsa or schnorr)', max_length=10)),
                ('signature_script_placeholder', models.CharField(help_text='Libauth template signature placeholder key. Example: key1.schnorr_signature.all_outputs', max_length=200)),
                ('sighash', models.CharField(blank=True, max_length=50, null=True)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signer_signatures', to='multisig.Signer')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_signatures', to='multisig.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='MultisigWalletSigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='Position of the signer in the multisig wallet')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multisig.Signer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multisig.MultisigWallet')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('wallet', 'index', 'signer')},
            },
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='signers',
            field=models.ManyToManyField(related_name='wallets', through='multisig.MultisigWalletSigner', to='multisig.Signer'),
        ),
    ]
