# Generated by Django 3.0.14 on 2025-06-28 07:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultisigTransactionProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address_index', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('origin', models.CharField(blank=True, help_text='Where the transaction was created. Could be a dapp url or wallet name', max_length=250, null=True)),
                ('purpose', models.CharField(blank=True, max_length=250, null=True)),
                ('transaction', models.TextField(help_text='Unsigned transaction hex')),
                ('transaction_hash', models.CharField(help_text='Computed hash of the unsigned transaction hex', max_length=64, unique=True)),
                ('source_outputs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The source utxos', null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('signed_transaction', models.TextField(blank=True, help_text='Signed transaction hex, final compilation result', null=True)),
                ('signed_transaction_hash', models.CharField(blank=True, help_text='Computed hash of the signed transaction', max_length=64, null=True)),
                ('txid', models.CharField(blank=True, help_text='Broadcasted signed transaction id', max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('signing_progress', models.CharField(blank=True, choices=[('unsigned', 'unsigned'), ('partially-signed', 'partially-signed'), ('fully-signed', 'fully-signed')], max_length=16, null=True)),
                ('broadcast_status', models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('done', 'done')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MultisigWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', django.contrib.postgres.fields.jsonb.JSONField(help_text='Wallet template')),
                ('locking_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Raw locking data', null=True)),
                ('locking_bytecode', models.CharField(blank=True, max_length=46, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_key', models.CharField(help_text="The signer's entity-key, Example: signer_1", max_length=255)),
                ('xpub', models.CharField(db_index=True, help_text='The xpub owned by the signer', max_length=512)),
                ('acknowledged', models.BooleanField(default=False, help_text='True if signer acknowledged the wallet')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='multisig.MultisigWallet')),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_index', models.PositiveSmallIntegerField()),
                ('signature_key', models.CharField(help_text='Concatenated template signer variable, sig algo and sighash. Example: key1.schnorr_signature.alloutputs', max_length=150)),
                ('signature_value', models.CharField(max_length=150)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multisig.Signer')),
                ('transaction_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='multisig.MultisigTransactionProposal')),
            ],
        ),
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multisig.MultisigWallet'),
        ),
        migrations.AddConstraint(
            model_name='signer',
            constraint=models.UniqueConstraint(fields=('wallet', 'entity_key', 'xpub'), name='unique_signer'),
        ),
    ]
