# Generated by Django 3.0.14 on 2025-05-14 06:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultisigTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultisigWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locking_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Raw locking data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, help_text="Wallet's cashaddress. The address derived from address index 0.", max_length=255, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multisig.MultisigTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SignerHdPublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="The signer's entity-key, Example: signer_1", max_length=255)),
                ('value', models.CharField(db_index=True, help_text='The xpub owned by the signer', max_length=512)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signer_hd_public_keys', to='multisig.MultisigWallet')),
            ],
        ),
    ]
