# Generated by Django 3.0.14 on 2025-05-26 03:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultisigTransactionProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address_index', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('transaction', models.TextField(help_text='Unsigned transaction hex')),
                ('source_outputs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='The source utxos', null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='signer',
            name='acknowledged',
            field=models.BooleanField(default=False, help_text='True if signer acknowledged the wallet'),
        ),
        migrations.AlterField(
            model_name='multisigwallet',
            name='locking_bytecode',
            field=models.CharField(blank=True, max_length=46, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='multisig.MultisigWallet'),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_index', models.PositiveSmallIntegerField()),
                ('signature_key', models.CharField(help_text='Concatenated template signer variable, sig algo and sighash. Example: key1.schnorr_signature.alloutputs', max_length=150)),
                ('signature_value', models.CharField(max_length=150)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multisig.Signer')),
                ('transaction_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='multisig.MultisigTransactionProposal')),
            ],
        ),
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multisig.MultisigWallet'),
        ),
    ]
