# Generated by Django 3.0.14 on 2025-07-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigwallet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multisig.Signer'),
        ),
    ]
