# Generated by Django 3.0.14 on 2025-05-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multisigwallet',
            name='address',
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='locking_bytecode',
            field=models.CharField(blank=True, max_length=46, null=True),
        ),
    ]
