# Generated by Django 3.0.14 on 2025-04-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigwalletsigner',
            name='signer_is_wallet_creator',
            field=models.BooleanField(default=False, help_text='True if this signer created this wallet'),
        ),
        migrations.AddField(
            model_name='signer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(blank=True, help_text='If present, transaction broadcasted to the network.', max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='signer',
            unique_together={('xpub', 'derivation_path', 'name')},
        ),
    ]
