# Generated by Django 3.0.14 on 2025-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0002_auto_20250526_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='transaction_hash',
            field=models.CharField(default='transactionhashdefault', help_text='Computed hash of the unsigned transaction hex', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
