# Generated by Django 3.0.14 on 2026-02-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0002_multisigwallet_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_record', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='signer',
            name='unique_signer',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='locking_bytecode',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='locking_data',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='template',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='acknowledged',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='entity_key',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='xpub',
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the wallet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='wallet_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='derivation_path',
            field=models.CharField(blank=True, help_text='The derivation path of the xpub', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='master_fingerprint',
            field=models.CharField(blank=True, help_text="The signer's xpub master fingerprint", max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the signer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='public_key',
            field=models.CharField(blank=True, help_text="The signer's xpub public key", max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='wallet_descriptor',
            field=models.TextField(blank=True, help_text="The BSMS wallet descriptor encrypted by the coordinator to this signer's public key", null=True),
        ),
        migrations.AddConstraint(
            model_name='signer',
            constraint=models.UniqueConstraint(fields=('wallet', 'public_key'), name='unique_signer'),
        ),
        migrations.AddField(
            model_name='keyrecord',
            name='published_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multisig.ServerIdentity'),
        ),
        migrations.AddField(
            model_name='keyrecord',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multisig.ServerIdentity'),
        ),
    ]
