# Generated by Django 3.0.14 on 2025-05-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0002_auto_20250514_0655'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='signerhdpublickey',
            constraint=models.UniqueConstraint(fields=('wallet', 'key', 'value'), name='unique_wallet_key_value'),
        ),
    ]
