# Generated by Django 3.0.14 on 2025-04-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0002_auto_20250421_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigwallet',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
