# Generated by Django 3.0.14 on 2025-09-23 03:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0002_multisigwallet_created_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='signer',
            name='unique_signer',
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='m',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='n',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='name',
            field=models.CharField(default='Unnamed Multisig Wallet', max_length=250),
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='wallet_hash',
            field=models.CharField(default='', help_text='The sha256 hash of the address 0 locking bytecode (The first set of lexicographically sorted public keys)', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signer',
            name='name',
            field=models.CharField(default='', help_text='Signers name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multisigwallet',
            name='template',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Wallet template', null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='entity_key',
            field=models.CharField(blank=True, help_text="The signer's entity-key, Example: signer_1", max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='signer',
            constraint=models.UniqueConstraint(fields=('wallet', 'xpub'), name='unique_signer'),
        ),
    ]
