# Generated by Django 3.0.14 on 2026-03-12 07:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_drop_assetsetting_favorites_slp_if_exists'),
        ('multisig', '0002_multisigwallet_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bip32Derivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('public_key', models.CharField(blank=True, help_text="Signer's public key", max_length=66, null=True)),
                ('master_fingerprint', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outpoint_transaction_hash', models.CharField(max_length=64)),
                ('outpoint_index', models.PositiveIntegerField()),
                ('redeem_script', models.TextField(blank=True, null=True)),
                ('spending_txid', models.CharField(blank=True, help_text='The txid where this was spent. It could be the proposal or other tx. This can be used to invalidate the proposal as `Conflicted` or flag it as `Broadcasted`.', max_length=64, null=True)),
                ('conflicting_proposal_identifier', models.CharField(blank=True, help_text='The unsigned transaction hash of the spending transaction that is different from the proposal.', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_record', models.TextField(help_text='An ECIES encrypted BSMS 1.0 key record')),
                ('audience_auth_public_key', models.CharField(blank=True, help_text='The auth public key of the intended audience for this key record', max_length=66, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unsigned_transaction_hex', models.TextField(help_text='The Unsigned transaction hex.')),
                ('unsigned_transaction_hash', models.CharField(help_text='The hash of the Unsigned transaction', max_length=64)),
                ('signed_transaction', models.TextField(blank=True, help_text='The Signed transaction hex. This could be a partially signed transaction. This updates as signing submissions are received.', null=True)),
                ('signed_transaction_hash', models.CharField(blank=True, help_text='The double sha256 hash of the Signed transaction', max_length=64, null=True)),
                ('proposal', models.TextField(blank=True, help_text='The original submitted serialized / encoded proposal data.', null=True)),
                ('proposal_format', models.CharField(blank=True, default='psbt', help_text='The format of the proposal data', max_length=50, null=True)),
                ('off_premise_transaction_broadcast', models.CharField(blank=True, help_text='If set transaction was broadcasted outside watchtower', max_length=64, null=True)),
                ('combined_psbt', models.TextField(blank=True, help_text='The combined psbts. Updated everytime new psbt comes in.', null=True)),
                ('coordinator_proposal_signature', models.CharField(blank=True, help_text='The coordinator/uploader signature over the unsigned_transaction_hash, using the Signer auth_public_key. Used for tamper detection / integrity check before cosigner signing.', max_length=512, null=True)),
                ('coordinator_proposal_signature_scheme', models.CharField(blank=True, default='schnorr', help_text="The signature scheme used for coordinator_proposal_signature ('schnorr' or 'ecdsa').", max_length=20)),
                ('txid', models.CharField(blank=True, help_text='The transaction ID (txid) of the broadcasted transaction, as seen and searchable on block explorers', max_length=64, null=True)),
                ('signing_progress', models.CharField(blank=True, choices=[('unsigned', 'unsigned'), ('partially-signed', 'partially-signed'), ('fully-signed', 'fully-signed')], max_length=16, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('broadcasted', 'Broadcasted'), ('broadcast_failed', 'Broadcast Failed'), ('mempool', 'In mempool'), ('confirmed', 'Confirmed'), ('conflicted', 'Conflicted')], default='pending', max_length=25)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text="List of errors: [{'type': 'broadcast', 'message': '...', 'timestamp': '...'}]")),
            ],
        ),
        migrations.CreateModel(
            name='Psbt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_hash', models.CharField(blank=True, help_text='The sha256 hash of the psbt payload is treated as utf8 string. This is only used for deduplication', max_length=64, null=True, unique=True)),
                ('standard', models.CharField(blank=True, default='psbt', max_length=50, null=True)),
                ('encoding', models.CharField(blank=True, default='base64', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_proposal', models.BooleanField(default=False, help_text='Whether this PSBT is the original proposal PSBT.')),
            ],
        ),
        migrations.CreateModel(
            name='ServerIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('public_key', models.CharField(max_length=66, unique=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='multisigtransactionproposal',
            name='wallet',
        ),
        migrations.RemoveConstraint(
            model_name='signer',
            name='unique_signer',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='locking_bytecode',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='locking_data',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='template',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='input_index',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='signature_key',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='signature_value',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='signer',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='transaction_proposal',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='acknowledged',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='entity_key',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='xpub',
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the wallet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='wallet_descriptor_id',
            field=models.CharField(blank=True, help_text='SHA256 hash of the canonical BSMS descriptor', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='wallet_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='public_key',
            field=models.CharField(blank=True, help_text="Signer's public key", max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='signature',
            field=models.CharField(blank=True, help_text='Signature hex string', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='auth_public_key',
            field=models.CharField(blank=True, help_text="The child non-hardened public key derived at 999/0 from this cosigner's xpub", max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='derivation_path',
            field=models.CharField(blank=True, help_text='The derivation path of the xpub', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='master_fingerprint',
            field=models.CharField(blank=True, help_text="The signer's xpub master fingerprint", max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the signer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='public_key',
            field=models.CharField(blank=True, help_text="The signer's xpub public key", max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='wallet_descriptor',
            field=models.TextField(blank=True, help_text="The BSMS wallet descriptor encrypted by the coordinator with this signer's public key", null=True),
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multisig_wallets', to='multisig.ServerIdentity'),
        ),
        migrations.AddConstraint(
            model_name='multisigwallet',
            constraint=models.UniqueConstraint(fields=('coordinator', 'wallet_descriptor_id'), name='unique_coordinator_wallet_descriptor'),
        ),
        migrations.AddConstraint(
            model_name='signer',
            constraint=models.UniqueConstraint(fields=('wallet', 'public_key'), name='unique_signer'),
        ),
        migrations.DeleteModel(
            name='MultisigTransactionProposal',
        ),
        migrations.AddField(
            model_name='psbt',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psbts', to='multisig.Proposal'),
        ),
        migrations.AddField(
            model_name='psbt',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psbts_submitted', to='multisig.Signer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multisig.Signer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='on_premise_transaction_broadcast',
            field=models.ForeignKey(blank=True, help_text='If set transaction was broadcasted thru watchtower.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TransactionBroadcast'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multisig.MultisigWallet'),
        ),
        migrations.AddField(
            model_name='keyrecord',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_records_published', to='multisig.ServerIdentity'),
        ),
        migrations.AddField(
            model_name='keyrecord',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_records', to='multisig.MultisigWallet'),
        ),
        migrations.AddField(
            model_name='input',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='multisig.Proposal'),
        ),
        migrations.AddField(
            model_name='bip32derivation',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bip32_derivation', to='multisig.Input'),
        ),
        
        migrations.AddField(
            model_name='signature',
            name='input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='multisig.Input'),
        ),
        migrations.AddField(
            model_name='signature',
            name='psbt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='multisig.Psbt'),
        ),
        migrations.AlterUniqueTogether(
            name='input',
            unique_together={('proposal', 'outpoint_transaction_hash', 'outpoint_index')},
        ),
        migrations.AlterUniqueTogether(
            name='bip32derivation',
            unique_together={('input', 'public_key')},
        ),
    ]
