# Generated by Django 3.0.14 on 2026-01-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0002_multisigwallet_created_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='signer',
            name='unique_signer',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='locking_bytecode',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='locking_data',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='template',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='acknowledged',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='entity_key',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='xpub',
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the wallet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='wallet_hash',
            field=models.CharField(blank=True, db_index=True, max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='coordinator',
            field=models.BooleanField(blank=True, default=False, help_text='True if the signer is the coordinator', null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='derivation_path',
            field=models.CharField(blank=True, help_text="The derivation path of the signer's xpub", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='master_fingerprint',
            field=models.CharField(blank=True, help_text="The master fingerprint of the signer's xpub", max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the signer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='pubkey_zero',
            field=models.CharField(blank=True, help_text="The public key of the signer's xpub at address index 0", max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='wallet_bsms_descriptor',
            field=models.TextField(blank=True, help_text='The bsms descriptor of the wallet curated for this signer', null=True),
        ),
        migrations.AddConstraint(
            model_name='signer',
            constraint=models.UniqueConstraint(fields=('wallet', 'pubkey_zero'), name='unique_signer'),
        ),
        migrations.AddConstraint(
            model_name='signer',
            constraint=models.UniqueConstraint(condition=models.Q(coordinator=True), fields=('wallet',), name='unique_coordinator_per_wallet'),
        ),
    ]
