# Generated by Django 3.0.14 on 2026-01-09 10:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0002_multisigwallet_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultisigWalletDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.TextField(help_text='The bsms descriptor')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='signer',
            name='unique_signer',
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the wallet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='wallet_hash',
            field=models.CharField(blank=True, db_index=True, max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the signer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='xpub_hash',
            field=models.CharField(blank=True, help_text='The hash256 of the hd public key', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='multisigwallet',
            name='template',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Wallet template', null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='acknowledged',
            field=models.BooleanField(blank=True, default=False, help_text='True if signer acknowledged the wallet', null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='entity_key',
            field=models.CharField(blank=True, help_text="The signer's entity-key, Example: signer_1", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='xpub',
            field=models.CharField(blank=True, db_index=True, help_text='The xpub owned by the signer', max_length=512, null=True),
        ),
        migrations.AddConstraint(
            model_name='signer',
            constraint=models.UniqueConstraint(fields=('wallet', 'xpub_hash'), name='unique_signer'),
        ),
        migrations.AddField(
            model_name='multisigwalletdescriptor',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_descriptors', to='multisig.Signer'),
        ),
    ]
