# Generated by Django 3.0.14 on 2026-01-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0002_multisigwallet_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultisigWalletDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.TextField(help_text='The bsms descriptor')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='signer',
            name='unique_signer',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='locking_bytecode',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='locking_data',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='template',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='acknowledged',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='entity_key',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='xpub',
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the wallet', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='wallet_hash',
            field=models.CharField(blank=True, db_index=True, max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the signer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='pubkey_zero',
            field=models.CharField(blank=True, help_text='The public key at address index 0', max_length=66, null=True),
        ),
        migrations.AddConstraint(
            model_name='signer',
            constraint=models.UniqueConstraint(fields=('wallet', 'pubkey_zero'), name='unique_signer'),
        ),
        migrations.AddField(
            model_name='multisigwalletdescriptor',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_descriptors', to='multisig.Signer'),
        ),
    ]
