# Generated by Django 3.0.14 on 2025-04-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0003_multisigwallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigwallet',
            name='address',
            field=models.CharField(default='testaddress', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
