# Generated by Django 3.0.14 on 2026-03-18 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0003_auto_20260312_0757'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='signer',
            name='unique_signer',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='wallet_descriptor',
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='wallet_descriptor',
            field=models.TextField(blank=True, help_text="The BSMS wallet descriptor encrypted by the coordinator with this signer's public key", null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='wallet_descriptor_wrapped_dek',
            field=models.TextField(blank=True, help_text="The AESGCM256 symmetric key created by coordinator. The key is the data encryption key of the wallet_descriptor. This key is then encrypted(wrapped) using ECIES with this signer's XPub public key", null=True),
        ),
        migrations.AlterField(
            model_name='keyrecord',
            name='audience_auth_public_key',
            field=models.CharField(blank=True, help_text='The auth public key of the intended audience for this key record, the one that can decrypt the key record.', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='keyrecord',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_records', to='multisig.MultisigWallet'),
        ),
        migrations.AddConstraint(
            model_name='signer',
            constraint=models.UniqueConstraint(fields=('wallet', 'auth_public_key'), name='unique_signer'),
        ),
    ]
