# Generated by Django 3.0.14 on 2026-01-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0003_auto_20260109_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multisigwallet',
            name='locking_bytecode',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='locking_data',
        ),
        migrations.RemoveField(
            model_name='multisigwallet',
            name='template',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='acknowledged',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='entity_key',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='xpub',
        ),
    ]
