# Generated by Django 3.0.14 on 2026-03-30 07:56

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0003_auto_20260312_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletConnectSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, help_text='Unique WalletConnect session topic (main identifier)', max_length=250, unique=True)),
                ('origin', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="Raw 'self' object from WalletConnect session")),
                ('origin_name', models.CharField(blank=True, help_text='Name of the dApp (from self.metadata.name)', max_length=250, null=True)),
                ('origin_url', models.URLField(blank=True, help_text='URL of the dApp', max_length=500, null=True)),
                ('peer', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="Raw 'peer' object from WalletConnect session")),
                ('peer_name', models.CharField(blank=True, db_index=True, help_text='Name of the connected wallet', max_length=250, null=True)),
                ('peer_url', models.URLField(blank=True, help_text='URL of the connected wallet', max_length=500, null=True)),
                ('accounts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of connected accounts/addresses', size=None)),
                ('expiry', models.BigIntegerField(blank=True, help_text='Session expiry timestamp', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is still active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WalletConnect Session',
                'verbose_name_plural': 'WalletConnect Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='signer',
            name='unique_signer',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='wallet_descriptor',
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='wallet_descriptor',
            field=models.TextField(blank=True, help_text="The BSMS wallet descriptor encrypted by the coordinator with this signer's public key", null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='wallet_descriptor_wrapped_dek',
            field=models.TextField(blank=True, help_text="The AESGCM256 symmetric key created by coordinator. The key is the data encryption key of the wallet_descriptor. This key is then encrypted(wrapped) using ECIES with this signer's XPub public key", null=True),
        ),
        migrations.AlterField(
            model_name='keyrecord',
            name='audience_auth_public_key',
            field=models.CharField(blank=True, help_text='The auth public key of the intended audience for this key record, the one that can decrypt the key record.', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='keyrecord',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_records', to='multisig.MultisigWallet'),
        ),
        migrations.AddConstraint(
            model_name='signer',
            constraint=models.UniqueConstraint(fields=('wallet', 'auth_public_key'), name='unique_signer'),
        ),
        migrations.AddField(
            model_name='walletconnectsession',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multisig.MultisigWallet'),
        ),
        migrations.AddIndex(
            model_name='walletconnectsession',
            index=models.Index(fields=['topic'], name='multisig_wa_topic_495546_idx'),
        ),
        migrations.AddIndex(
            model_name='walletconnectsession',
            index=models.Index(fields=['peer_name'], name='multisig_wa_peer_na_c6e5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='walletconnectsession',
            index=models.Index(fields=['peer_url'], name='multisig_wa_peer_ur_a32408_idx'),
        ),
        migrations.AddIndex(
            model_name='walletconnectsession',
            index=models.Index(fields=['origin_url'], name='multisig_wa_origin__e4c13d_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletconnectsession',
            constraint=models.UniqueConstraint(fields=('topic',), name='unique_walletconnect_topic'),
        ),
        migrations.AddConstraint(
            model_name='walletconnectsession',
            constraint=models.UniqueConstraint(fields=('topic', 'peer_name'), name='unique_topic_peer'),
        ),
    ]
