# Generated by Django 3.0.14 on 2026-02-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0003_auto_20260202_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveridentity',
            name='public_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
