# Generated by Django 3.0.14 on 2025-06-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0003_multisigtransactionproposal_transaction_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultisigTransactionProposalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(help_text='Computed hash of the unsigned transaction', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('broadcasted', 'Broadcasted')], default='pending', max_length=20)),
                ('transaction_proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='multisig.MultisigTransactionProposal')),
            ],
        ),
    ]
