# Generated by Django 3.0.14 on 2025-04-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0004_multisigwallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigwallet',
            name='derivation_path',
            field=models.CharField(default="m/44'/145'/0'/0", help_text='Shared BIP32 derivation path (excluding address index).', max_length=120),
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='primary_address',
            field=models.CharField(default='bchtest:ppftrvu9wzxtfhp3q3lk5ytkyqajez47eunu5waz8y', help_text='Multisig address derived using the shared derivation path at address index 0. Used to uniquely identify this wallet', max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multisigwallet',
            name='address',
            field=models.CharField(help_text='Multisig address derived using the shared derivation path at address index 0. Used to uniquely identify this wallet', max_length=120, unique=True),
        ),
    ]
