# Generated by Django 3.0.14 on 2026-02-03 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0004_auto_20260202_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigwallet',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multisig_wallets', to='multisig.ServerIdentity'),
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='wallet_descriptor_id',
            field=models.CharField(blank=True, help_text='SHA256 hash of the canonical BSMS descriptor', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='keyrecord',
            name='published_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_for_key_records', to='multisig.ServerIdentity'),
        ),
        migrations.AlterField(
            model_name='keyrecord',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_key_records', to='multisig.ServerIdentity'),
        ),
    ]
