# Generated by Django 3.0.14 on 2026-03-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0004_auto_20260330_0756'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('unsigned_transaction_hash',), name='unique_active_proposal'),
        ),
    ]
