# Generated by Django 3.0.14 on 2025-06-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0004_multisigtransactionproposalstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multisigtransactionproposalstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='txid',
            field=models.CharField(blank=True, help_text='Broadcasted signed transaction id', max_length=64, null=True, unique=True),
        ),
    ]
