# Generated by Django 3.0.14 on 2026-02-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0005_auto_20260203_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveridentity',
            name='public_key',
            field=models.CharField(max_length=66, unique=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='public_key',
            field=models.CharField(blank=True, help_text="The signer's xpub public key", max_length=66, null=True),
        ),
    ]
