# Generated by Django 3.0.14 on 2025-04-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0005_auto_20250429_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multisigwallet',
            name='address',
        ),
    ]
