# Generated by Django 3.0.14 on 2025-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0005_auto_20250610_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('broadcasted', 'Broadcasted')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='MultisigTransactionProposalStatus',
        ),
    ]
