# Generated by Django 3.0.14 on 2025-06-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0006_auto_20250610_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigwallet',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
