# Generated by Django 3.0.14 on 2026-02-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0006_auto_20260203_0854'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='multisigwallet',
            constraint=models.UniqueConstraint(fields=('coordinator', 'wallet_descriptor_id'), name='unique_coordinator_wallet_descriptor'),
        ),
    ]
