# Generated by Django 3.0.14 on 2025-04-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0006_remove_multisigwallet_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signer',
            unique_together={('xpub', 'name')},
        ),
        migrations.RemoveField(
            model_name='signer',
            name='derivation_path',
        ),
    ]
