# Generated by Django 3.0.14 on 2026-02-05 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0007_auto_20260203_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outpoint_transaction_hash', models.CharField(max_length=64)),
                ('outpoint_index', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, help_text='The purpose of the transaction', max_length=250, null=True)),
                ('origin', models.CharField(blank=True, help_text='The origin of the transaction. Can be a wallet or dapp url', max_length=250, null=True)),
                ('unsigned_transaction_hex', models.TextField(help_text='The Unsigned transaction hex.')),
                ('unsigned_transaction_hash', models.CharField(help_text='The hash of the Unsigned transaction', max_length=64)),
                ('signed_transaction', models.TextField(blank=True, help_text='The Signed transaction hex. This could be a partially signed transaction. This updates as signing submissions are received.', null=True)),
                ('signed_transaction_hash', models.CharField(blank=True, help_text='The double sha256 hash of the Signed transaction', max_length=64, null=True)),
                ('txid', models.CharField(blank=True, help_text='The transaction ID (txid) of the broadcasted transaction, as seen and searchable on block explorers', max_length=64, null=True)),
                ('signing_progress', models.CharField(blank=True, choices=[('unsigned', 'unsigned'), ('partially-signed', 'partially-signed'), ('fully-signed', 'fully-signed')], max_length=16, null=True)),
                ('broadcast_status', models.CharField(choices=[('pending', 'pending'), ('done', 'done')], default='pending', max_length=10)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multisig.MultisigWallet')),
            ],
        ),
        migrations.CreateModel(
            name='SigningSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField()),
                ('payload_format', models.CharField(blank=True, default='psbt', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_submissions', to='multisig.Proposal')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_submissions', to='multisig.Signer')),
            ],
            options={
                'unique_together': {('proposal', 'signer')},
            },
        ),
        migrations.RemoveField(
            model_name='signature',
            name='signer',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='transaction_proposal',
        ),
        migrations.DeleteModel(
            name='MultisigTransactionProposal',
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
        migrations.AddField(
            model_name='input',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='multisig.Proposal'),
        ),
        migrations.AlterUniqueTogether(
            name='input',
            unique_together={('outpoint_transaction_hash', 'outpoint_index')},
        ),
    ]
