# Generated by Django 3.0.14 on 2025-06-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0007_multisigwallet_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='signed_transaction',
            field=models.TextField(blank=True, help_text='Signed transaction hex, final compilation result', null=True),
        ),
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='signed_transaction_hash',
            field=models.CharField(blank=True, help_text='Computed hash of the signed transaction', max_length=64, null=True),
        ),
    ]
