# Generated by Django 3.0.14 on 2025-04-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0007_auto_20250429_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signertransactionsignature',
            old_name='signature_script_placeholder',
            new_name='signature_identifier',
        ),
    ]
