# Generated by Django 3.0.14 on 2025-04-29 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0008_auto_20250429_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multisigwallet',
            name='template',
        ),
    ]
