# Generated by Django 3.0.14 on 2025-06-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0008_auto_20250612_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='signing_progress',
            field=models.CharField(blank=True, choices=[('unsigned', 'unsigned'), ('partially-signed', 'partially-signed'), ('fully-signed', 'fully-signed')], max_length=16, null=True),
        ),
    ]
