# Generated by Django 3.0.14 on 2026-02-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0008_auto_20260205_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='purpose',
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal',
            field=models.TextField(blank=True, help_text='The serialized / encoded proposal data', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_format',
            field=models.CharField(blank=True, default='psbt', help_text='The format of the proposal data', max_length=50, null=True),
        ),
    ]
