# Generated by Django 3.0.14 on 2026-02-10 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0009_auto_20260206_0604'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='signingsubmission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='signingsubmission',
            name='signer',
        ),
    ]
