# Generated by Django 3.0.14 on 2025-04-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0009_remove_multisigwallet_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multisigwallet',
            old_name='primary_address',
            new_name='primary_multisig_address',
        ),
    ]
