# Generated by Django 3.0.14 on 2025-06-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0009_multisigtransactionproposal_signing_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='broadcast',
            field=models.CharField(choices=[('pending', 'pending'), ('cancelled', 'cancelled'), ('done', 'done')], default='pending', max_length=20),
        ),
    ]
