# Generated by Django 3.0.14 on 2025-06-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0010_multisigtransactionproposal_broadcast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multisigtransactionproposal',
            old_name='broadcast',
            new_name='broadcast_status',
        ),
    ]
