# Generated by Django 3.0.14 on 2026-02-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0010_auto_20260210_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='redeem_script',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(help_text="Signer's public key", max_length=66)),
                ('signature', models.CharField(help_text='Signature hex string', max_length=160)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='multisig.Input')),
            ],
        ),
    ]
