# Generated by Django 3.0.14 on 2026-02-10 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0011_auto_20260210_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='signing_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='multisig.SigningSubmission'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='multisig.Input'),
        ),
    ]
