# Generated by Django 3.0.14 on 2025-06-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0011_auto_20250613_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multisigtransactionproposal',
            name='status',
        ),
    ]
