# Generated by Django 3.0.14 on 2025-06-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0012_remove_multisigtransactionproposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
