# Generated by Django 3.0.14 on 2026-02-10 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0012_auto_20260210_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bip32Derivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('public_key', models.CharField(blank=True, help_text="Signer's public key", max_length=66, null=True, unique=True)),
                ('master_fingerprint', models.CharField(blank=True, max_length=8, null=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bip32_derivations', to='multisig.Input')),
            ],
        ),
    ]
