# Generated by Django 3.0.14 on 2026-02-10 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0013_bip32derivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bip32derivation',
            name='input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bip32_derivation', to='multisig.Input'),
        ),
    ]
