# Generated by Django 3.0.14 on 2025-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0013_multisigtransactionproposal_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigwallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='multisigwallet',
            name='version',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
