# Generated by Django 3.0.14 on 2025-06-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0014_auto_20250616_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
