# Generated by Django 3.0.14 on 2026-02-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0014_auto_20260210_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='signingsubmission',
            name='payload_hash',
            field=models.CharField(blank=True, help_text='The sha256 hash of the payload. Payload is treated as utf8 string. This is only used for deduplication', max_length=64, null=True),
        ),
    ]
