# Generated by Django 3.0.14 on 2025-06-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0015_multisigtransactionproposal_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='origin',
            field=models.CharField(blank=True, help_text='Where the transaction was created. Could be a dapp url or wallet name', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='multisigtransactionproposal',
            name='purpose',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
