# Generated by Django 3.0.14 on 2026-02-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0015_signingsubmission_payload_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveridentity',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serveridentity',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serveridentity',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
