# Generated by Django 3.0.14 on 2026-02-13 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0016_auto_20260213_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyrecord',
            name='published_for',
        ),
        migrations.AddField(
            model_name='keyrecord',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_records_received', to='multisig.ServerIdentity'),
        ),
        migrations.AlterField(
            model_name='keyrecord',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_records_published', to='multisig.ServerIdentity'),
        ),
    ]
