# Generated by Django 3.0.14 on 2026-02-13 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0017_auto_20260213_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='server_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_identity', to='multisig.ServerIdentity'),
        ),
    ]
