# Generated by Django 3.0.14 on 2026-02-13 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0018_signer_server_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multisig.ServerIdentity'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='server_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signers', to='multisig.ServerIdentity'),
        ),
    ]
