# Generated by Django 3.0.14 on 2026-02-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0019_auto_20260213_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='spent_on_transaction',
            field=models.CharField(blank=True, help_text='The txid where this was spent. It could be the proposal or other tx. This can be used to invalidate the proposal or flag it as `Broadcasted`.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='broadcast_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('broadcasted', 'Broadcasted'), ('mempool', 'In mempool'), ('confirmed', 'Confirmed'), ('conflicted', 'Conflicted'), ('failed', 'Failed to broadcast')], default='pending', max_length=25),
        ),
    ]
