# Generated by Django 3.0.14 on 2026-02-16 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_drop_assetsetting_favorites_slp_if_exists'),
        ('multisig', '0020_auto_20260213_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='spent_on_transaction',
        ),
        migrations.AddField(
            model_name='input',
            name='conflicting_proposal_identifier',
            field=models.CharField(blank=True, help_text='The unsigned transaction hash of the spending transaction that is different from the proposal.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='spending_txid',
            field=models.CharField(blank=True, help_text='The txid where this was spent. It could be the proposal or other tx. This can be used to invalidate the proposal as `Conflicted` or flag it as `Broadcasted`.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='off_premise_transaction_broadcast',
            field=models.CharField(blank=True, help_text='If set transaction was broadcasted outside watchtower', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='on_premise_transaction_broadcast',
            field=models.ForeignKey(blank=True, help_text='If set transaction was broadcasted thru watchtower.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.TransactionBroadcast'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal',
            field=models.TextField(blank=True, help_text='The serialized / encoded proposal data.', null=True),
        ),
    ]
