# Generated by Django 3.0.14 on 2026-02-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0021_auto_20260216_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bip32derivation',
            name='public_key',
            field=models.CharField(blank=True, help_text="Signer's public key", max_length=66, null=True),
        ),
    ]
