# Generated by Django 3.0.14 on 2026-02-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0022_auto_20260216_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bip32derivation',
            unique_together={('input', 'public_key')},
        ),
    ]
