# Generated by Django 3.0.14 on 2026-02-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0023_auto_20260220_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyrecord',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='server_identity',
        ),
        migrations.AddField(
            model_name='keyrecord',
            name='audience_auth_public_key',
            field=models.CharField(blank=True, help_text='The auth public key of the intended audience for this key record', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='signer',
            name='auth_public_key',
            field=models.CharField(blank=True, help_text="The child non-hardened public key derived at 999/0 from this cosigner's xpub", max_length=66, null=True),
        ),
    ]
