# Generated by Django 3.0.14 on 2026-02-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0023_auto_20260220_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signer',
            name='server_identity',
        ),
        migrations.AddField(
            model_name='signer',
            name='cosigner_auth_public_key',
            field=models.CharField(blank=True, help_text="The double sha256 child non-hardened public key derived at 999/0 from this cosigner's xpub", max_length=66, null=True),
        ),
    ]
