# Generated by Django 3.0.14 on 2026-02-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0024_auto_20260223_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyrecord',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_records', to='multisig.MultisigWallet'),
        ),
        migrations.AlterField(
            model_name='keyrecord',
            name='key_record',
            field=models.TextField(help_text='An ECIES encrypted BSMS 1.0 key record'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multisig.Signer'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='wallet_descriptor',
            field=models.TextField(blank=True, help_text="The BSMS wallet descriptor encrypted by the coordinator with this signer's public key", null=True),
        ),
    ]
