# Generated by Django 3.0.14 on 2026-02-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0025_auto_20260223_0854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='input',
            unique_together={('proposal', 'outpoint_transaction_hash', 'outpoint_index')},
        ),
    ]
