# Generated by Django 3.0.14 on 2026-02-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0026_auto_20260224_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('broadcasted', 'Broadcasted'), ('mempool', 'In mempool'), ('confirmed', 'Confirmed'), ('conflicted', 'Conflicted'), ('failed', 'Failed to broadcast')], default='pending', max_length=25),
        ),
    ]
