# Generated by Django 3.0.14 on 2026-02-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0027_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_combined',
            field=models.TextField(blank=True, help_text='The combined proposal from Signing Submissions. Updated everytime new signing submission comes in.', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal',
            field=models.TextField(blank=True, help_text='The original submitted serialized / encoded proposal data.', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('broadcasted', 'Broadcasted'), ('mempool', 'In mempool'), ('confirmed', 'Confirmed'), ('conflicted', 'Conflicted'), ('failed', 'Failed to broadcast'), ('deleted', 'Deleted')], default='pending', max_length=25),
        ),
    ]
