# Generated by Django 3.0.14 on 2026-03-06 01:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0027_proposal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psbt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_hash', models.CharField(blank=True, help_text='The sha256 hash of the psbt payload is treated as utf8 string. This is only used for deduplication', max_length=64, null=True, unique=True)),
                ('standard', models.CharField(blank=True, default='psbt', max_length=50, null=True)),
                ('encoding', models.CharField(blank=True, default='base64', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_proposal', models.BooleanField(default=False, help_text='Whether this PSBT is the original proposal PSBT.')),
            ],
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='broadcast_status',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='signing_submission',
        ),
        migrations.AddField(
            model_name='proposal',
            name='combined_psbt',
            field=models.TextField(blank=True, help_text='The combined psbts. Updated everytime new psbt comes in.', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='coordinator_proposal_signature',
            field=models.CharField(blank=True, help_text='The coordinator/uploader signature over the unsigned_transaction_hash, using the Signer auth_public_key. Used for tamper detection / integrity check before cosigner signing.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='coordinator_proposal_signature_scheme',
            field=models.CharField(blank=True, default='schnorr', help_text="The signature scheme used for coordinator_proposal_signature ('schnorr' or 'ecdsa').", max_length=20),
        ),
        migrations.AddField(
            model_name='proposal',
            name='errors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text="List of errors: [{'type': 'broadcast', 'message': '...', 'timestamp': '...'}]"),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal',
            field=models.TextField(blank=True, help_text='The original submitted serialized / encoded proposal data.', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('broadcasted', 'Broadcasted'), ('broadcast_failed', 'Broadcast Failed'), ('mempool', 'In mempool'), ('confirmed', 'Confirmed'), ('conflicted', 'Conflicted')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='signature',
            name='input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='multisig.Input'),
        ),
        migrations.DeleteModel(
            name='SigningSubmission',
        ),
        migrations.AddField(
            model_name='psbt',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psbts', to='multisig.Proposal'),
        ),
        migrations.AddField(
            model_name='psbt',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psbts_submitted', to='multisig.Signer'),
        ),
        migrations.AddField(
            model_name='signature',
            name='psbt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='multisig.Psbt'),
        ),
    ]
