# Generated by Django 3.0.14 on 2026-02-26 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0028_auto_20260225_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='combined_psbt',
            field=models.TextField(blank=True, help_text='The combined psbts. Updated everytime new psbt comes in.', null=True),
        ),
        migrations.CreateModel(
            name='Psbt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('standard', models.CharField(blank=True, default='psbt', max_length=50, null=True)),
                ('encoding', models.CharField(blank=True, default='base64', max_length=50, null=True)),
                ('hash', models.CharField(blank=True, help_text='The sha256 hash of the psbt payload is treated as utf8 string. This is only used for deduplication', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_proposal', models.BooleanField(default=False, help_text='Whether this PSBT is the original proposal PSBT.')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psbts', to='multisig.Proposal')),
            ],
        ),
        migrations.AddField(
            model_name='signature',
            name='psbt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='multisig.Psbt'),
        ),
    ]
