# Generated by Django 3.0.14 on 2026-02-26 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0029_auto_20260226_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psbt',
            old_name='hash',
            new_name='content_hash',
        ),
    ]
