# Generated by Django 3.0.14 on 2026-02-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0030_auto_20260226_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='broadcast_status',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='proposal_combined',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='signing_submission',
        ),
        migrations.DeleteModel(
            name='SigningSubmission',
        ),
    ]
