# Generated by Django 3.0.14 on 2026-02-27 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0031_auto_20260226_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='psbt',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psbts_submitted', to='multisig.Signer'),
        ),
        migrations.AlterField(
            model_name='psbt',
            name='content_hash',
            field=models.CharField(blank=True, help_text='The sha256 hash of the psbt payload is treated as utf8 string. This is only used for deduplication', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='multisig.Input'),
        ),
    ]
