# Generated by Django 3.0.14 on 2026-03-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multisig', '0032_auto_20260227_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='coordinator_proposal_signature',
            field=models.CharField(blank=True, help_text='The coordinator/uploader signature over the unsigned_transaction_hash, using the Signer auth_public_key. Used for tamper detection / integrity check before cosigner signing.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='coordinator_proposal_signature_scheme',
            field=models.CharField(blank=True, default='schnorr', help_text="The signature scheme used for coordinator_proposal_signature ('schnorr' or 'ecdsa').", max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('broadcasted', 'Broadcasted'), ('mempool', 'In mempool'), ('confirmed', 'Confirmed'), ('conflicted', 'Conflicted'), ('failed', 'Failed to broadcast')], default='pending', max_length=25),
        ),
    ]
