# Generated by Django 3.0.14 on 2023-01-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgpinfo',
            name='public_key_hash',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pgpinfo',
            name='signature',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
