# Generated by Django 3.0.14 on 2023-01-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20230110_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgpinfo',
            name='public_key_hash',
            field=models.CharField(max_length=70),
        ),
    ]
