# Generated by Django 3.0.14 on 2023-01-24 10:24

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20230109_2243'),
        ('chat', '0003_auto_20230110_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('public_key', models.TextField()),
                ('public_key_hash', models.CharField(max_length=70)),
                ('signature', models.TextField()),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_identity', to='main.Address')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_started', to='main.Address')),
                ('to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_received', to='main.Address')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.DeleteModel(
            name='PgpInfo',
        ),
    ]
