# Generated by Django 3.0.14 on 2023-01-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20230124_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatidentity',
            options={'verbose_name_plural': 'Chat identities'},
        ),
    ]
