# Generated by Django 3.0.14 on 2023-01-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20230126_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_messaged',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
