# Generated by Django 3.0.14 on 2023-01-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_last_messaged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_messaged']},
        ),
    ]
