# Generated by Django 3.0.14 on 2023-01-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20230128_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='topic',
            field=models.TextField(unique=True),
        ),
    ]
