# Generated by Django 3.0.3 on 2020-02-24 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, unique=True)),
                ('transactions_count', models.IntegerField(default=0)),
                ('createdby', models.DateTimeField(blank=True, null=True)),
                ('updatedby', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenid', models.CharField(max_length=200)),
                ('confirmation_limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SlpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slpaddress', to='main.Token')),
                ('transactions', models.ManyToManyField(to='main.Transaction')),
            ],
            options={
                'verbose_name': 'Slp Address',
                'verbose_name_plural': 'Slp Addresses',
            },
        ),
    ]
