# Generated by Django 3.0.7 on 2021-03-13 09:08

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BchAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=200, unique=True)),
                ('scanned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'BCH Address',
                'verbose_name_plural': 'BCH Addresses',
            },
        ),
        migrations.CreateModel(
            name='BlockHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, default=0, unique=True)),
                ('transactions_count', models.IntegerField(default=0)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('currentcount', models.IntegerField(default=0)),
                ('problematic', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('unparsed', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SendTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Send To',
                'verbose_name_plural': 'Send To',
            },
        ),
        migrations.CreateModel(
            name='SlpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'SLP Address',
                'verbose_name_plural': 'SLP Addresses',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('tokenid', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('confirmation_limit', models.IntegerField(default=0)),
                ('decimals', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('name', 'tokenid')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(db_index=True, max_length=200)),
                ('address', models.CharField(db_index=True, max_length=500, null=True)),
                ('amount', models.FloatField(db_index=True, default=0)),
                ('acknowledged', models.BooleanField(default=False)),
                ('source', models.CharField(db_index=True, max_length=200, null=True)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscribed', models.BooleanField(db_index=True, default=False)),
                ('spent_index', models.IntegerField(db_index=True, default=0)),
                ('blockheight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.BlockHeight')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Token')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ManyToManyField(related_name='subscription', to='main.SendTo')),
                ('bch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='main.BchAddress')),
                ('slp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='main.SlpAddress')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='main.Token')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('telegram_user_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('slack_user_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('subscriptions', models.ManyToManyField(related_name='subscriber', to='main.Subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='slpaddress',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='slpaddress', to='main.Transaction'),
        ),
        migrations.AddField(
            model_name='bchaddress',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='bchaddress', to='main.Transaction'),
        ),
    ]
