# Generated by Django 3.0.7 on 2021-03-23 02:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockheight',
            name='problematic',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='blockheight',
            name='unparsed',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='token',
            name='tokenid',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
