# Generated by Django 3.0.3 on 2020-02-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='saved_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
