# Generated by Django 3.0.3 on 2020-02-24 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaction_saved_by_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='blockheight',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.BlockHeight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
