# Generated by Django 3.0.7 on 2021-03-26 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_transaction_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='spent_index',
            new_name='index',
        ),
        migrations.AddField(
            model_name='transaction',
            name='spend_block_height',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='spent_transactions', to='main.BlockHeight'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='spent',
            field=models.BooleanField(default=False),
        ),
    ]
