# Generated by Django 3.0.7 on 2021-03-26 13:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210326_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.CharField(blank=True, max_length=500, null=True)),
                ('telegram_user_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('slack_user_details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name': 'Send To',
                'verbose_name_plural': 'Send To',
            },
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subscriptions',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='address',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='token',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='bch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='main.BchAddress'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='slp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='main.SlpAddress'),
        ),
        migrations.DeleteModel(
            name='SendTo',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AddField(
            model_name='subscription',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='main.Recipient'),
        ),
    ]
