# Generated by Django 3.0.7 on 2021-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210329_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
