# Generated by Django 3.0.3 on 2020-02-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200224_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='saved_by_client',
            new_name='acknowledge',
        ),
    ]
