# Generated by Django 3.0.7 on 2021-03-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210329_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
