# Manually generated by developer

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200225_0442'),
    ]

    def create_super_user(apps, schema_editor):
        from django.contrib.auth.models import User
        user = User.objects.create_user('admin', 'admin@watchtower.com', 'admindefault2020')
        user.is_superuser = True
        user.is_staff = True
        user.save()
        
    

    operations = [
        migrations.RunPython(create_super_user),
    ]
