# Generated by Django 3.0.3 on 2020-02-27 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_load_fixtures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slpaddress',
            name='token',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.Token'),
            preserve_default=False,
        ),
    ]
