# Generated by Django 3.0.14 on 2021-05-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subscription_websocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockheight',
            name='requires_full_scan',
            field=models.BooleanField(default=True),
        ),
    ]
