# Generated by Django 3.0.14 on 2021-05-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_subscription_websocket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockHeight',
            new_name='Block',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='blockheight',
            new_name='block',
        ),
    ]
