# Generated by Django 3.0.3 on 2020-03-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200227_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='slpdb_api',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
