# Generated by Django 3.0.14 on 2021-05-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_blockheight_requires_full_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='nft_token_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.Token'),
        ),
        migrations.AddField(
            model_name='token',
            name='token_ticker',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='token_type',
            field=models.IntegerField(default=1),
        ),
    ]
