# Generated by Django 3.0.14 on 2021-05-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210517_0553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='SLPToken',
        ),
    ]
