# Generated by Django 3.0.3 on 2020-03-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_token_slpdb_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='slpdb_api',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
