# Generated by Django 3.0.14 on 2021-05-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210517_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='spent',
            new_name='acknowledged_by_subscriber',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created_datetime',
            new_name='first_seen',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='index',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='spend_block_height',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='token',
        ),
        migrations.AddField(
            model_name='transaction',
            name='confirmed_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lock_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='version',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
