# Generated by Django 3.0.14 on 2021-06-15 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210527_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='bch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='main.BchAddress'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='main.Recipient'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='slp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='main.SlpAddress'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='blockheight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.BlockHeight'),
        ),
    ]
