# Generated by Django 3.0.14 on 2021-05-17 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210517_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=500, null=True)),
                ('amount', models.FloatField(db_index=True, default=0)),
                ('index', models.IntegerField(db_index=True, default=0)),
                ('lock_script', models.TextField()),
                ('slp_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SLPToken')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='main.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_script', models.TextField()),
                ('parent_output', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input', to='main.Output')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='main.Transaction')),
            ],
        ),
    ]
