# Generated by Django 3.0.14 on 2021-05-17 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_input_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_address', models.CharField(db_index=True, max_length=200, unique=True)),
                ('bch_address', models.CharField(db_index=True, max_length=200, unique=True)),
                ('slp_address', models.CharField(db_index=True, max_length=200, unique=True)),
                ('public_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('txs', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='main.Output')),
            ],
        ),
        migrations.RemoveField(
            model_name='slpaddress',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='bch',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='slp',
        ),
        migrations.DeleteModel(
            name='BchAddress',
        ),
        migrations.DeleteModel(
            name='SlpAddress',
        ),
        migrations.AddField(
            model_name='subscription',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='main.Address'),
            preserve_default=False,
        ),
    ]
