# Generated by Django 3.0.3 on 2020-03-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='slpdb_api',
        ),
    ]
