# Generated by Django 3.0.3 on 2020-03-06 09:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_token_slpdb_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
