# Generated by Django 3.0.14 on 2021-06-20 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210618_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='main.Project'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='main.Project'),
        ),
    ]
