# Generated by Django 3.0.3 on 2020-03-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_subscriber_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='scanning',
            field=models.BooleanField(default=True),
        ),
    ]
