# Generated by Django 3.0.14 on 2021-06-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210621_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='acknowledged',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
