# Generated by Django 3.0.3 on 2020-03-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_transaction_scanning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='scanning',
            field=models.BooleanField(default=False),
        ),
    ]
