# Generated by Django 3.0.3 on 2020-03-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200310_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockheight',
            name='currentcount',
            field=models.IntegerField(default=0),
        ),
    ]
