# Generated by Django 3.0.14 on 2021-06-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210622_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slpaddress',
            name='transactions',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='bch',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='slp',
        ),
        migrations.DeleteModel(
            name='BchAddress',
        ),
        migrations.DeleteModel(
            name='SlpAddress',
        ),
    ]
