# Generated by Django 3.0.14 on 2021-06-23 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210622_0534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('txid', 'address', 'index')},
        ),
    ]
