# Generated by Django 3.0.3 on 2020-03-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_blockheight_currentcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='token',
            new_name='tokens',
        ),
    ]
