# Generated by Django 3.0.14 on 2021-06-25 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210623_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.Address'),
        ),
    ]
