# Generated by Django 3.0.3 on 2020-03-17 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_auto_20200317_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='data',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='tokens',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='main.SendTo')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='main.Token')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscription',
            field=models.ManyToManyField(related_name='subscriber', to='main.Subscription'),
        ),
    ]
