# Generated by Django 3.0.3 on 2020-03-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200317_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='target_address',
        ),
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
