# Generated by Django 3.0.14 on 2021-06-25 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210625_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='address_fk',
            new_name='address',
        ),
    ]
