# Generated by Django 3.0.3 on 2020-03-18 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20200317_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
