# Generated by Django 3.0.14 on 2021-06-25 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210625_0037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('txid', 'address', 'index')},
        ),
    ]
