# Generated by Django 3.0.3 on 2020-03-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_subscriber_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscription',
            field=models.ManyToManyField(null=True, related_name='subscriber', to='main.Subscription'),
        ),
    ]
