# Generated by Django 3.0.14 on 2021-06-26 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210626_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='record_type',
            field=models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_records', to='main.Token'),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='txid',
            field=models.CharField(db_index=True, default='', max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
