# Generated by Django 3.0.14 on 2021-06-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210626_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='spend_block_height',
        ),
    ]
