# Generated by Django 3.0.14 on 2021-07-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210630_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='main.Wallet'),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_history_records', to='main.Token'),
        ),
    ]
