# Generated by Django 3.0.3 on 2020-04-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200320_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('txid', 'address')},
        ),
    ]