# Generated by Django 3.0.14 on 2021-07-01 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210701_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='wallethistory',
            options={'verbose_name': 'Wallet history', 'verbose_name_plural': 'Wallet histories'},
        ),
        migrations.AlterUniqueTogether(
            name='wallethistory',
            unique_together={('wallet', 'txid')},
        ),
    ]
