# Generated by Django 3.0.3 on 2020-05-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_create_default_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tokenid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
