# Generated by Django 3.0.14 on 2021-07-02 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210701_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_datetime',
            new_name='date_created',
        ),
    ]
