# Generated by Django 3.0.14 on 2021-07-03 02:05

from django.db import migrations
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210702_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockheight',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='wallethistory',
            options={'ordering': ['-date_created'], 'verbose_name': 'Wallet history', 'verbose_name_plural': 'Wallet histories'},
        ),
        migrations.AlterModelManagers(
            name='address',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='blockheight',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='recipient',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='token',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='wallet',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='wallethistory',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
