# Generated by Django 3.0.3 on 2020-07-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_subscription_bch'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='queued',
            field=models.BooleanField(default=False),
        ),
    ]
