# Generated by Django 3.0.3 on 2020-07-29 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_transaction_queued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='queued',
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Token'),
        ),
    ]
