# Generated by Django 3.0.14 on 2021-07-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210722_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='tx_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
