# Generated by Django 3.0.3 on 2020-07-29 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20200729_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='blockheight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.BlockHeight'),
        ),
    ]
