# Generated by Django 3.0.14 on 2021-08-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210723_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='decimals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_type',
            field=models.IntegerField(null=True),
        ),
    ]
