# Generated by Django 3.0.14 on 2021-08-12 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20210811_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='logo_url',
            new_name='image_url',
        ),
    ]
