# Generated by Django 3.0.3 on 2020-08-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200729_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='address',
        ),
        migrations.AddField(
            model_name='subscription',
            name='address',
            field=models.ManyToManyField(related_name='subscription', to='main.SendTo'),
        ),
    ]
