# Generated by Django 3.0.3 on 2020-08-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200805_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='bchaddress',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
    ]
