# Generated by Django 3.0.14 on 2021-08-28 08:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210812_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='nft_token_group_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
