# Generated by Django 3.0.14 on 2021-09-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_token_nft_token_group_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='web_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
