# Generated by Django 3.0.7 on 2020-09-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_subscriber_telegram_user_details'),
        ('main', '0041_subscriber_slack_user_details'),
    ]

    operations = [
    ]
