# Generated by Django 3.0.14 on 2021-09-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20210901_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_path',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
