# Generated by Django 3.0.7 on 2021-02-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_merge_20200905_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bchaddress',
            name='address',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blockheight',
            name='number',
            field=models.IntegerField(db_index=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='slpaddress',
            name='address',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='tokenid',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
