# Generated by Django 3.0.14 on 2021-09-22 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_token_thumbnail_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='image_url',
            new_name='original_image_url',
        ),
    ]
