# Generated by Django 3.0.7 on 2021-02-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210221_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='acknowledge',
            new_name='acknowledged',
        ),
    ]
