# Generated by Django 3.0.14 on 2021-09-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20210922_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='medium_image_url',
            field=models.URLField(blank=True),
        ),
    ]
