# Generated by Django 3.0.14 on 2021-11-11 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_token_medium_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='nft_token_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.Token'),
        ),
    ]
