# Generated by Django 3.0.7 on 2021-03-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20210224_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockheight',
            name='transaction_fail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blockheight',
            name='transaction_success',
            field=models.IntegerField(default=0),
        ),
    ]
