# Generated by Django 3.0.7 on 2021-03-02 07:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20210302_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockheight',
            name='error_logs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
