# Generated by Django 3.0.14 on 2021-11-27 01:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20211111_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletNftToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acquired', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_dispensed', models.DateTimeField(blank=True, null=True)),
                ('acquisition_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='main.Transaction')),
                ('dispensation_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='main.Transaction')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='main.Token')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='main.Wallet')),
            ],
        ),
    ]
