# Generated by Django 3.0.14 on 2021-12-10 03:36

from django.db import migrations
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_walletnfttoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walletnfttoken',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='walletnfttoken',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
