# Generated by Django 3.0.7 on 2021-03-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20210302_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockheight',
            name='transaction_fail',
        ),
        migrations.RemoveField(
            model_name='blockheight',
            name='transaction_success',
        ),
    ]
