# Generated by Django 3.0.14 on 2021-12-10 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20211210_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walletnfttoken',
            options={'ordering': ['-date_acquired']},
        ),
        migrations.AlterField(
            model_name='walletnfttoken',
            name='acquisition_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='main.Transaction'),
        ),
    ]
