# Generated by Django 3.0.14 on 2022-02-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20211210_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_hash',
            field=models.CharField(db_index=True, max_length=70, unique=True),
        ),
    ]
