# Generated by Django 3.0.7 on 2021-03-02 08:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20210302_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockheight',
            old_name='error_logs',
            new_name='err_reasons',
        ),
        migrations.AddField(
            model_name='blockheight',
            name='err_txs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
