# Generated by Django 3.0.7 on 2021-03-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20210302_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockheight',
            old_name='err_reasons',
            new_name='genesis',
        ),
        migrations.RemoveField(
            model_name='blockheight',
            name='err_txs',
        ),
    ]
