# Generated by Django 3.0.14 on 2022-11-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20220330_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tx_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='tx_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
