# Generated by Django 3.0.7 on 2021-03-03 03:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20210302_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockheight',
            name='problematic',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='blockheight',
            name='genesis',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
