# Generated by Django 3.0.7 on 2021-03-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20210303_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='spentIndex',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscribed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
