# Generated by Django 3.0.14 on 2022-11-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20221114_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPriceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(db_index=True, max_length=5)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('price_value', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='usd_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
