# Generated by Django 3.0.14 on 2022-11-23 08:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20221116_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='market_prices',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
