# Generated by Django 3.0.7 on 2021-03-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20210305_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscription',
            new_name='subscriptions',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='scanning',
        ),
    ]
