# Generated by Django 3.0.14 on 2022-11-24 06:44

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_wallethistory_market_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_currency', models.CharField(default='USD', max_length=5)),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='main.Wallet')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
