# Generated by Django 3.0.7 on 2021-03-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20210310_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Token'),
        ),
    ]
