# Generated by Django 3.0.14 on 2023-01-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_walletpreferences'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wallethistory',
            managers=[
            ],
        ),
    ]
