# Generated by Django 3.0.7 on 2021-03-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20210310_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='decimals',
            field=models.IntegerField(default=0),
        ),
    ]
