# Generated by Django 3.0.14 on 2023-02-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_transactionmetaattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='mint_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
