# Generated by Django 3.0.7 on 2021-03-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_token_decimals'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('name', 'tokenid')},
        ),
    ]
