# Generated by Django 3.0.7 on 2021-03-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20210311_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockheight',
            name='genesis',
        ),
    ]
