# Generated by Django 3.0.7 on 2021-03-12 13:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_remove_blockheight_genesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockheight',
            name='unparsed',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
