# Generated by Django 3.0.14 on 2023-03-22 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20230307_0310'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallethistory',
            unique_together={('wallet', 'txid', 'token')},
        ),
    ]
