# Generated by Django 3.0.14 on 2023-04-03 01:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20230322_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTokenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('symbol', models.CharField(max_length=100)),
                ('decimals', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('nft_details', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='token',
            name='capability',
        ),
        migrations.RemoveField(
            model_name='token',
            name='commitment',
        ),
        migrations.RemoveField(
            model_name='token',
            name='is_cashtoken',
        ),
        migrations.CreateModel(
            name='CashNonFungibleToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('commitment', models.CharField(blank=True, default='', max_length=255)),
                ('capability', models.CharField(blank=True, choices=[('mutable', 'Mutable'), ('minting', 'Minting'), ('none', 'None')], default='', max_length=10)),
                ('current_txid', models.CharField(max_length=70)),
                ('current_index', models.PositiveIntegerField()),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='main.CashTokenInfo')),
            ],
            options={
                'verbose_name_plural': 'CashToken NFTs',
                'unique_together': {('category', 'current_index', 'current_txid')},
            },
        ),
        migrations.CreateModel(
            name='CashFungibleToken',
            fields=[
                ('category', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fungible_tokens', to='main.CashTokenInfo')),
            ],
            options={
                'verbose_name_plural': 'CashToken Fungible Tokens',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='cashtoken_ft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CashFungibleToken'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cashtoken_nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CashNonFungibleToken'),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='cashtoken_ft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_history_records', to='main.CashFungibleToken'),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='cashtoken_nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_history_records', to='main.CashNonFungibleToken'),
        ),
    ]
