# Generated by Django 3.0.14 on 2023-04-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20230403_0156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashnonfungibletoken',
            unique_together={('current_index', 'current_txid')},
        ),
    ]
