# Generated by Django 3.0.14 on 2023-04-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20230403_0537'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallethistory',
            unique_together={('wallet', 'txid', 'token', 'cashtoken_ft', 'cashtoken_nft')},
        ),
    ]
