# Generated by Django 3.0.14 on 2023-04-04 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20230403_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashfungibletoken',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fungible_tokens', to='main.CashTokenInfo'),
        ),
        migrations.AlterField(
            model_name='cashnonfungibletoken',
            name='info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='main.CashTokenInfo'),
        ),
    ]
