# Generated by Django 3.0.14 on 2023-05-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20230517_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
