# Generated by Django 3.0.14 on 2023-05-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_transaction_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
