# Generated by Django 3.0.14 on 2023-05-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20230524_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
