# Generated by Django 3.0.14 on 2023-07-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20230524_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtokeninfo',
            name='decimals',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
