# Generated by Django 3.0.14 on 2023-07-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20230731_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='token_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
