# Generated by Django 3.0.14 on 2023-08-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_address_token_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='token_address',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='telegram_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='web_url',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True),
        ),
    ]
