# Generated by Django 3.0.14 on 2023-08-11 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20230806_0014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallethistory',
            unique_together={('wallet', 'txid', 'cashtoken_ft'), ('wallet', 'txid', 'token'), ('wallet', 'txid', 'cashtoken_nft')},
        ),
    ]
