# Generated by Django 3.0.14 on 2023-09-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20230806_0014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallethistory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='wallethistory',
            constraint=models.UniqueConstraint(condition=models.Q(('cashtoken_ft', None), ('cashtoken_nft', None)), fields=('wallet', 'txid', 'token', 'amount', 'record_type'), name='both_ctft_ctnft_none'),
        ),
        migrations.AddConstraint(
            model_name='wallethistory',
            constraint=models.UniqueConstraint(condition=models.Q(cashtoken_ft=None), fields=('wallet', 'txid', 'token', 'amount', 'record_type', 'cashtoken_nft'), name='ctft_none'),
        ),
        migrations.AddConstraint(
            model_name='wallethistory',
            constraint=models.UniqueConstraint(condition=models.Q(cashtoken_nft=None), fields=('wallet', 'txid', 'token', 'amount', 'record_type', 'cashtoken_ft'), name='ctnft_none'),
        ),
        migrations.AddConstraint(
            model_name='wallethistory',
            constraint=models.UniqueConstraint(condition=models.Q(cashtoken_nft=None), fields=('wallet', 'txid', 'token', 'amount', 'record_type', 'cashtoken_ft', 'cashtoken_nft'), name='ctft_ctnft_not_none'),
        ),
    ]