# Generated by Django 3.0.14 on 2023-10-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20230909_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='post_save_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
