# Generated by Django 3.0.14 on 2023-10-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20230909_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='auth_nonce',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='auth_token',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
