# Generated by Django 3.0.14 on 2023-10-04 08:10

from django.db import migrations
from django.utils.crypto import get_random_string

def populate_tokens(apps, schema_editor):
    Wallet = apps.get_model('main', 'Wallet')
    for wallet in Wallet.objects.filter(auth_token__isnull=True):
        unique_token = get_random_string(40)
        while Wallet.objects.filter(auth_token=unique_token).exists():
            unique_token = get_random_string(40)
        wallet.auth_token = unique_token
        wallet.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_wallet_auth_token'),
    ]

    operations = [
        migrations.RunPython(populate_tokens),
    ]