# Generated by Django 3.0.14 on 2023-10-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_transaction_post_save_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='walletnfttoken',
            name='date_dispensed',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
