# Generated by Django 3.0.14 on 2023-10-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_populate_wallet_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='auth_nonce',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
