# Generated by Django 3.0.14 on 2023-10-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20231006_0654'),
        ('main', '0075_auto_20231006_0505'),
    ]

    operations = [
    ]
