# Generated by Django 3.0.14 on 2023-10-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_merge_20231013_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='record_type',
            field=models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], db_index=True, max_length=10),
        ),
    ]
