# Generated by Django 3.0.14 on 2023-12-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20231016_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_path',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
