# Generated by Django 3.0.14 on 2023-12-06 04:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20231206_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), size=None), blank=True, db_index=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='senders',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), size=None), blank=True, db_index=True, default=list, size=None),
        ),
    ]
