# Generated by Django 3.0.14 on 2023-12-06 04:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_auto_20231206_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        )
    ]
