# Generated by Django 3.0.14 on 2024-01-26 17:15

from django.db import migrations, models
import django.utils.timezone
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_auto_20231206_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionBroadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=70)),
                ('tx_hex', models.TextField()),
                ('num_retries', models.IntegerField(default=1)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_succeeded', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
