# Generated by Django 3.0.14 on 2023-12-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_auto_20231206_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
