# Generated by Django 3.0.14 on 2024-01-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_transactionbroadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionbroadcast',
            name='date_succeeded',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionbroadcast',
            name='num_retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactionbroadcast',
            name='txid',
            field=models.CharField(db_index=True, max_length=70),
        ),
    ]
