# Generated by Django 3.0.14 on 2024-02-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_transactionbroadcast_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpricelog',
            name='currency',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assetpricelog',
            name='relative_currency',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
