# Generated by Django 3.0.14 on 2024-03-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_auto_20240227_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpreferences',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
