# Generated by Django 3.0.14 on 2024-03-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_walletpreferences_wallet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletpreferences',
            name='wallet_name',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
