# Generated by Django 3.0.14 on 2024-04-08 06:59

from django.db import migrations, models
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20240322_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletShard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shard', models.CharField(db_index=True, max_length=350)),
                ('first_identifier', models.CharField(max_length=64)),
                ('second_identifier', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
