# Generated by Django 3.0.14 on 2024-05-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_auto_20240506_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletshard',
            name='shard',
            field=models.CharField(max_length=400, primary_key=True, serialize=False),
        ),
    ]
