# Generated by Django 3.0.14 on 2024-07-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_auto_20240513_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_balance_check',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_utxo_scan_succeeded',
            field=models.BooleanField(null=True),
        ),
    ]
