# Generated by Django 3.0.14 on 2024-11-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_auto_20241120_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddressApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField(blank=True, help_text='Name of the App/Dapp where the wallet_address was connected to', null=True)),
                ('app_url', models.TextField(blank=True, help_text='URL of the App/Dapp where the wallet_address was connected to', null=True)),
                ('wallet_address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
