# Generated by Django 3.0.14 on 2024-11-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_walletaddressapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaddressapp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='walletaddressapp',
            name='wallet_hash',
            field=models.CharField(blank=True, help_text='Helps group wallet addresses', max_length=70, null=True),
        ),
    ]
