# Generated by Django 3.0.14 on 2024-11-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_auto_20241125_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaddressapp',
            name='app_icon',
            field=models.TextField(blank=True, help_text='URL of the App/Dapp Icon', null=True),
        ),
    ]
