# Generated by Django 3.0.14 on 2024-11-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_auto_20241129_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
