# Generated by Django 3.0.14 on 2024-12-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_auto_20241129_0725'),
        ('main', '0094_min_required_version_0_20_2_20241126_0950'),
    ]

    operations = [
    ]
