# Generated by Django 3.0.14 on 2024-12-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_walletaddressapp_app_icon'),
        ('main', '0096_merge_20241203_0219'),
    ]

    operations = [
    ]
