# Generated by Django 3.0.14 on 2025-01-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_appcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashnonfungibletoken',
            name='fixed_supply',
            field=models.BooleanField(blank=True, help_text='Null means unknown', null=True),
        ),
    ]
