# Generated by Django 3.0.14 on 2025-03-24 06:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_cashnonfungibletoken_fixed_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appcontrol',
            name='name',
        ),
        migrations.AddField(
            model_name='appcontrol',
            name='enabled_countries',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='appcontrol',
            name='feature_name',
            field=models.CharField(choices=[('CASH_IN', 'Cash In'), ('P2P_EXCHANGE', 'P2P Exchange'), ('MARKETPLACE', 'Marketplace'), ('WALLET_CONNECT', 'Wallet Connect'), ('GIFTS', 'Gifts'), ('COLLECTIBLES', 'Collectibles'), ('ANYHEDGE', 'Anyhedge'), ('MAP', 'Map'), ('MERCHANT_ADMIN', 'Merchant Admin'), ('MERCHANT_CASH_OUT', 'Merchant Cash Out')], max_length=100, null=True, unique=True),
        ),
    ]
