# Generated by Django 3.0.14 on 2025-03-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_auto_20250324_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcontrol',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
