# Generated by Django 3.0.14 on 2025-08-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_auto_20250324_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpricelog',
            name='currency_ft_token',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asset_price_logs', to='main.CashFungibleToken'),
        ),
        migrations.AddField(
            model_name='assetpricelog',
            name='relative_currency_ft_token',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relative_asset_price_logs', to='main.CashFungibleToken'),
        ),
        migrations.AlterField(
            model_name='assetpricelog',
            name='price_value',
            field=models.DecimalField(decimal_places=8, max_digits=25),
        ),
    ]
