# Generated by Django 3.0.14 on 2025-08-22 06:07

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_auto_20250818_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(db_index=True, max_length=70)),
                ('record_type', models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], db_index=True, max_length=10)),
                ('amount', models.FloatField(db_index=True, default=0)),
                ('senders', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), size=None), blank=True, default=list, size=None)),
                ('recipients', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), size=None), blank=True, default=list, size=None)),
                ('tx_fee', models.FloatField(blank=True, null=True)),
                ('tx_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('usd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_prices', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='main.Address')),
                ('cashtoken_ft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_history_records', to='main.CashFungibleToken')),
                ('cashtoken_nft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_history_records', to='main.CashNonFungibleToken')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_history_records', to='main.Token')),
            ],
            options={
                'verbose_name': 'Contract History',
                'verbose_name_plural': 'Contract Histories',
                'ordering': ['-tx_timestamp', '-date_created'],
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='contracthistory',
            constraint=models.UniqueConstraint(condition=models.Q(('cashtoken_ft', None), ('cashtoken_nft', None)), fields=('address', 'txid', 'token', 'amount', 'record_type'), name='both_ctft_ctnft_contract_none'),
        ),
        migrations.AddConstraint(
            model_name='contracthistory',
            constraint=models.UniqueConstraint(condition=models.Q(cashtoken_ft=None), fields=('address', 'txid', 'token', 'amount', 'record_type', 'cashtoken_nft'), name='ctft_contract_none'),
        ),
        migrations.AddConstraint(
            model_name='contracthistory',
            constraint=models.UniqueConstraint(condition=models.Q(cashtoken_nft=None), fields=('address', 'txid', 'token', 'amount', 'record_type', 'cashtoken_ft'), name='ctnft_contract_none'),
        ),
        migrations.AddConstraint(
            model_name='contracthistory',
            constraint=models.UniqueConstraint(condition=models.Q(cashtoken_nft=None), fields=('address', 'txid', 'token', 'amount', 'record_type', 'cashtoken_ft', 'cashtoken_nft'), name='ctft_ctnft_not_contract_none'),
        ),
    ]
