# Generated by Django 3.0.14 on 2025-09-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_auto_20250822_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='publicize_wallets',
            field=models.BooleanField(default=False),
        ),
    ]
