# Generated by Django 3.0.14 on 2025-08-29 02:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_auto_20250822_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracthistory',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='contracthistory',
            name='senders',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='senders',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), blank=True, default=list, size=None),
        ),
    ]
