# Generated by Django 3.0.14 on 2025-09-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_project_publicize_wallets'),
        ('main', '0104_auto_20250829_0221'),
    ]

    operations = [
    ]
