# Generated by Django 3.0.14 on 2025-09-08 06:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0105_merge_20250902_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_hash', models.CharField(db_index=True, default='', max_length=70, unique=True)),
                ('custom_list', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('favorites', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
