# Generated by Django 3.0.14 on 2025-09-15 05:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_assetsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsetting',
            name='unlisted_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
