# Generated by Django 3.0.14 on 2025-11-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_assetsetting_unlisted_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionbroadcast',
            name='price_log',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_broadcasts', to='main.AssetPriceLog'),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='price_log',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_histories', to='main.AssetPriceLog'),
        ),
        migrations.AddIndex(
            model_name='wallethistory',
            index=models.Index(condition=models.Q(wallet__isnull=False), fields=['wallet', '-tx_timestamp', '-date_created'], name='wallet_history_wallet_time_idx'),
        ),
    ]
