# Generated by Django 3.0.14 on 2025-11-03 00:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0108_auto_20251102_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpricelog',
            name='source_price_logs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='IDs of source price logs used in calculation', null=True),
        ),
    ]
