# Generated by Django 3.0.14 on 2025-11-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_assetpricelog_source_price_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpricelog',
            name='calculation',
            field=models.CharField(blank=True, help_text='Calculation formula for derived prices', max_length=200, null=True),
        ),
    ]
