# Generated by Django 3.0.14 on 2025-11-03 05:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_assetpricelog_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionbroadcast',
            name='output_fiat_amounts',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Map of output index to fiat amount details. Format: {"0": {"fiat_amount": "100.50", "fiat_currency": "PHP", "recipient": "bitcoincash:qr..."}}', null=True),
        ),
    ]
