# Generated by Django 3.0.14 on 2025-11-03 08:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_transactionbroadcast_output_fiat_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='fiat_amounts',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='User-entered fiat amounts by currency. Format: {"PHP": 100.50, "USD": 1.75}', null=True),
        ),
    ]
