# Generated by Django 3.0.14 on 2025-11-16 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_wallethistory_fiat_amounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallethistory',
            name='fiat_amounts',
        ),
    ]
