# Generated by Django 3.0.14 on 2026-01-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_wallethistory_fiat_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmetaattribute',
            name='key',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
