# Generated by Django 3.0.14 on 2025-11-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_remove_wallethistory_fiat_amounts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(condition=models.Q(('spending_txid__isnull', False), models.Q(_negated=True, spending_txid='')), fields=['spending_txid', 'address'], name='txn_spending_txid_addr_idx'),
        ),
    ]
