# Generated by Django 3.0.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0115_assetsetting_favorites_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='paytaca_app_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]






