# Generated by Django 3.0.14 on 2025-12-17 06:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_wallet_paytaca_app_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsetting',
            name='favorites',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
