# Generated by Django 3.0.14 on 2026-01-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_auto_20251217_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmetaattribute',
            name='key',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
