# Generated by Django 3.0.14 on 2026-01-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_auto_20260107_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashnonfungibletoken',
            name='with_bcmr_metadata',
            field=models.BooleanField(db_index=True, default=False, help_text='True if BCMR indexer returned metadata for this category'),
        ),
    ]
