# Generated by Django 3.0.14 on 2026-01-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_addressbook_addressbookaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='addressbookaddress',
            name='address_type',
            field=models.CharField(choices=[('bch', 'BCH'), ('ct', 'CashToken')], default='bch', max_length=3),
        ),
    ]
