# Generated by Django 3.0.14 on 2026-01-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0119_cashnonfungibletoken_with_bcmr_metadata"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # State already has no `favorites_slp` field; only enforce DB cleanup.
            state_operations=[],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE main_assetsetting DROP COLUMN IF EXISTS favorites_slp;",
                    reverse_sql=(
                        "ALTER TABLE main_assetsetting "
                        "ADD COLUMN IF NOT EXISTS favorites_slp jsonb NOT NULL DEFAULT '[]'::jsonb;"
                    ),
                )
            ],
        )
    ]

