# Generated by Django 3.0.14 on 2026-02-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_drop_assetsetting_favorites_slp_if_exists'),
        ('main', '0119_auto_20260116_0325'),
    ]

    operations = [
    ]
