# Generated by Django 3.0.14 on 2026-02-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0121_merge_20260223_0208'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addressbookaddress',
            unique_together={('address_book', 'address')},
        ),
    ]
