# Generated by Django 3.0.14 on 2026-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_auto_20260223_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='advance_subscription',
            field=models.BooleanField(default=False, db_index=True),
        ),
    ]
