# Generated by Django 3.0.14 on 2026-05-10 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_add_address_composite_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='addr_wallet_advsub_path_idx',
        ),
    ]
