# Generated by Django 3.0.14 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_auto_20260510_0218'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(
                fields=['wallet', 'advance_subscription', 'address_path'],
                name='addr_wallet_advsub_path_idx'
            ),
        ),
    ]
