# Generated by Django 3.0.14 on 2026-05-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_add_address_composite_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
