# Generated by Django 3.0.14 on 2026-06-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_recipient_webhook_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_path',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
