# Generated by Django 3.0.14 on 2026-08-25 01:43

from django.db import migrations, models
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0130_remove_walletactivity_amount'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='walletactivity',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterField(
            model_name='walletactivity',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
