# Generated by Django 3.0.14 on 2023-08-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purelypeer', '0003_auto_20230809_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='merchant_signer_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
