# Generated by Django 3.0.14 on 2023-08-15 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purelypeer', '0004_vault_merchant_signer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault',
            name='merchant_receiving_address',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='merchant_signer_address',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='receiving_pubkey',
        ),
        migrations.RemoveField(
            model_name='vault',
            name='receiving_pubkey_hash',
        ),
    ]
