# Generated by Django 3.0.14 on 2023-09-04 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purelypeer', '0006_auto_20230904_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='voucher',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
