# Generated by Django 3.0.14 on 2023-04-03 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('wallet_address', models.CharField(blank=True, max_length=50, null=True)),
                ('is_arbiter', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('default_fiat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peers', to='rampp2p.FiatCurrency')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rampp2p.Peer')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rampp2p.PaymentType')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('SELL', 'Sell'), ('BUY', 'Buy')], max_length=4)),
                ('price_type', models.CharField(choices=[('FIXED', 'Fixed'), ('FLOATING', 'Floating')], max_length=10)),
                ('fixed_price', models.FloatField()),
                ('floating_price', models.FloatField()),
                ('trade_floor', models.FloatField()),
                ('trade_ceiling', models.FloatField()),
                ('crypto_amount', models.FloatField()),
                ('time_limit', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rampp2p.CryptoCurrency')),
                ('fiat_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rampp2p.FiatCurrency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rampp2p.Peer')),
                ('payment_methods', models.ManyToManyField(to='rampp2p.PaymentMethod')),
            ],
        ),
    ]
