# Generated by Django 3.0.14 on 2023-04-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='payment_methods',
            field=models.ManyToManyField(related_name='ads', to='rampp2p.PaymentMethod'),
        ),
    ]
