# Generated by Django 3.0.14 on 2023-04-04 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0003_auto_20230403_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rampp2p.Peer'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='rampp2p.PaymentType'),
        ),
    ]
