# Generated by Django 3.0.14 on 2023-04-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0004_auto_20230404_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
