# Generated by Django 3.0.14 on 2023-04-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0005_auto_20230404_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(max_length=100),
        ),
    ]
