# Generated by Django 3.0.14 on 2023-04-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0006_auto_20230404_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='abbrev',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='fiatcurrency',
            name='abbrev',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
