# Generated by Django 3.0.14 on 2023-04-04 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0007_auto_20230404_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(to='rampp2p.Peer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiat_amount', models.FloatField(editable=False)),
                ('locked_price', models.FloatField(editable=False)),
                ('contract_address', models.CharField(blank=True, max_length=50, null=True)),
                ('is_appealed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='rampp2p.Ad')),
                ('arbiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rampp2p.Peer')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rampp2p.Chat')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='rampp2p.Peer')),
                ('crypto_currency', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='rampp2p.CryptoCurrency')),
                ('fiat_currency', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='rampp2p.FiatCurrency')),
                ('payment_methods', models.ManyToManyField(to='rampp2p.PaymentMethod')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SBM', 'Submitted'), ('CNF', 'Confirmed'), ('PD', 'Paid'), ('APL', 'Appealed'), ('RLS', 'Released'), ('RFN', 'Refunded'), ('CNCL', 'Canceled')], editable=False, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rampp2p.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(editable=False, max_length=4000)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rampp2p.Chat')),
                ('from_peer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rampp2p.Peer')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(editable=False, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rampp2p.Message')),
            ],
        ),
    ]
