# Generated by Django 3.0.14 on 2023-04-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0011_auto_20230404_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='fixed_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='floating_price',
            field=models.FloatField(null=True),
        ),
    ]
