# Generated by Django 3.0.14 on 2023-04-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0012_auto_20230404_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='from_peer',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
