# Generated by Django 3.0.14 on 2023-04-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0013_auto_20230404_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fiat_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='locked_price',
            field=models.FloatField(),
        ),
    ]
