# Generated by Django 3.0.14 on 2023-04-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0016_auto_20230410_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='peer',
            name='wallet_hash',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peer',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
    ]
