# Generated by Django 3.0.14 on 2023-04-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0018_auto_20230412_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CNCL', 'Cancel'), ('RLS', 'Release'), ('RFN', 'Refund')], editable=False, max_length=5)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='created_appeals', to='rampp2p.Peer')),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_appeals', to='rampp2p.Order')),
            ],
        ),
    ]
