# Generated by Django 3.0.14 on 2023-04-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0024_auto_20230417_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_appealed',
        ),
    ]
