# Generated by Django 3.0.14 on 2023-05-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0027_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fiat_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='arbiter_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='crypto_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='seller_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='peer',
            name='arbiter_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
