# Generated by Django 3.0.14 on 2023-05-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0028_auto_20230502_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fiat_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
