# Generated by Django 3.0.14 on 2023-05-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0031_auto_20230502_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='arbiter_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
