# Generated by Django 3.0.14 on 2023-05-08 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0035_auto_20230504_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='order',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rampp2p.Order'),
        ),
    ]
