# Generated by Django 3.0.14 on 2023-05-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0036_auto_20230508_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='peer',
            name='arbiter_address',
        ),
        migrations.AddField(
            model_name='peer',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peer',
            name='public_key',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
