# Generated by Django 3.0.14 on 2023-05-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0037_auto_20230512_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='arbiter_address',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='buyer_address',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='seller_address',
        ),
    ]
