# Generated by Django 3.0.14 on 2023-05-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0038_auto_20230512_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='txid',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('FUND', 'Fund'), ('REFUND', 'Refund'), ('ARBITER_RELEASE', 'Arbiter Release'), ('SELLER_RELEASE', 'Seller Release')], max_length=50)),
                ('txid', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rampp2p.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='rampp2p.Transaction')),
            ],
        ),
    ]
