# Generated by Django 3.0.14 on 2023-05-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0039_auto_20230518_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('FUND', 'Fund'), ('REFUND', 'Refund'), ('RELEASE', 'Release')], max_length=50),
        ),
    ]
