# Generated by Django 3.0.14 on 2023-05-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0043_auto_20230525_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='ad',
            name='time_duration_choice',
            field=models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (60, '1 hour'), (300, '5 hours'), (720, '12 hours'), (1440, '1 day')], default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='time_duration_choice',
            field=models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (60, '1 hour'), (300, '5 hours'), (720, '12 hours'), (1440, '1 day')], default=15),
            preserve_default=False,
        ),
    ]
