# Generated by Django 3.0.14 on 2023-05-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0044_auto_20230526_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('SBM', 'Submitted'), ('ESCRW_PN', 'Escrow pending'), ('ESCRW', 'Escrowed'), ('PD_PN', 'Paid Pending'), ('PD', 'Paid'), ('CNCL_APL', 'Appealed for Cancel'), ('RLS_APL', 'Appealed for Release'), ('RFN_APL', 'Appealed for Refund'), ('RLS_PN', 'Release pending'), ('RLS', 'Released'), ('RFN_PN', 'Refund pending'), ('RFN', 'Refunded'), ('CNCL', 'Canceled')], editable=False, max_length=10),
        ),
    ]
