# Generated by Django 3.0.14 on 2023-06-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0045_auto_20230530_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('SBM', 'Submitted'), ('ESCRW_PN', 'Escrow Pending'), ('ESCRW', 'Escrowed'), ('PD_PN', 'Paid Pending'), ('PD', 'Paid'), ('RLS_APL', 'Appealed for Release'), ('RFN_APL', 'Appealed for Refund'), ('RLS_PN', 'Release Pending'), ('RLS', 'Released'), ('RFN_PN', 'Refund Pending'), ('RFN', 'Refunded'), ('CNCL', 'Canceled')], editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('ESCROW', 'Escrow'), ('REFUND', 'Refund'), ('RELEASE', 'Release')], max_length=50),
        ),
    ]
