# Generated by Django 3.0.14 on 2023-06-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0046_auto_20230602_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='type',
            field=models.CharField(choices=[('RLS', 'Release'), ('RFN', 'Refund')], editable=False, max_length=10),
        ),
    ]
