# Generated by Django 3.0.14 on 2023-06-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0049_marketprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarketPrice',
            new_name='MarketRate',
        ),
        migrations.RenameField(
            model_name='marketrate',
            old_name='currency_symbol',
            new_name='currency',
        ),
    ]
