# Generated by Django 3.0.14 on 2023-06-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0050_auto_20230623_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ad',
            name='floating_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=18),
        ),
    ]
