# Generated by Django 3.0.14 on 2023-06-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0051_auto_20230626_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='crypto_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ad',
            name='trade_ceiling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ad',
            name='trade_floor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
