# Generated by Django 3.0.14 on 2023-06-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0052_auto_20230626_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('public_key', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('wallet_hash', models.CharField(max_length=100, unique=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
