# Generated by Django 3.0.14 on 2023-06-26 10:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0053_arbiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arbiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arbitrated_orders', to='rampp2p.Arbiter'),
        ),
        migrations.CreateModel(
            name='ArbiterFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('from_peer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='arbiter_feedbacks', to='rampp2p.Peer')),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='arbiter_feedbacks', to='rampp2p.Order')),
                ('to_arbiter', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='rampp2p.Arbiter')),
            ],
        ),
    ]
