# Generated by Django 3.0.14 on 2023-07-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0055_remove_peer_is_arbiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='abbrev',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='fiatcurrency',
            old_name='abbrev',
            new_name='symbol',
        ),
    ]
