# Generated by Django 3.0.14 on 2023-07-31 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0058_auto_20230728_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rampp2p.Order'),
        ),
    ]
