# Generated by Django 3.0.14 on 2023-08-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0059_auto_20230731_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('SBM', 'Submitted'), ('CNF', 'Confirmed'), ('ESCRW_PN', 'Escrow Pending'), ('ESCRW', 'Escrowed'), ('PD_PN', 'Paid Pending'), ('PD', 'Paid'), ('RLS_APL', 'Appealed for Release'), ('RFN_APL', 'Appealed for Refund'), ('RLS_PN', 'Release Pending'), ('RLS', 'Released'), ('RFN_PN', 'Refund Pending'), ('RFN', 'Refunded'), ('CNCL', 'Canceled')], max_length=10),
        ),
    ]
