# Generated by Django 3.0.14 on 2023-08-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0060_auto_20230810_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
