# Generated by Django 3.0.14 on 2023-08-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0061_transaction_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_address',
            new_name='address',
        ),
    ]
