# Generated by Django 3.0.14 on 2023-08-15 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0062_auto_20230811_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rampp2p.Ad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='arbiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arbitrated_orders', to='rampp2p.Arbiter'),
        ),
        migrations.AlterField(
            model_name='order',
            name='crypto_currency',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rampp2p.CryptoCurrency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fiat_currency',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rampp2p.FiatCurrency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to='rampp2p.Peer'),
        ),
    ]
