# Generated by Django 3.0.14 on 2023-08-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0064_auto_20230815_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='verifying',
            field=models.BooleanField(default=True),
        ),
    ]
