# Generated by Django 3.0.14 on 2023-08-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0065_transaction_verifying'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='type',
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('SBM', 'Submitted'), ('CNF', 'Confirmed'), ('ESCRW_PN', 'Escrow Pending'), ('ESCRW', 'Escrowed'), ('PD_PN', 'Paid Pending'), ('PD', 'Paid'), ('APL', 'Appealed'), ('RLS_PN', 'Release Pending'), ('RLS', 'Released'), ('RFN_PN', 'Refund Pending'), ('RFN', 'Refunded'), ('CNCL', 'Canceled')], max_length=10),
        ),
    ]
