# Generated by Django 3.0.14 on 2023-09-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0066_auto_20230829_0529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='appeal',
            old_name='is_approved_at',
            new_name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='is_closed_at',
        ),
        migrations.AddField(
            model_name='appeal',
            name='reasons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='type',
            field=models.CharField(choices=[('RLS', 'Release'), ('RFN', 'Refund')], default='RLS', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
