# Generated by Django 3.0.14 on 2023-09-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0067_auto_20230904_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='type',
            field=models.CharField(choices=[('RLS', 'Release'), ('RFN', 'Refund')], max_length=10),
        ),
    ]
