# Generated by Django 3.0.14 on 2023-09-08 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0068_auto_20230907_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('SELL', 'Sell'), ('BUY', 'Buy')], max_length=4)),
                ('price_type', models.CharField(choices=[('FIXED', 'Fixed'), ('FLOATING', 'Floating')], max_length=10)),
                ('fixed_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('floating_price', models.DecimalField(decimal_places=2, default=1, max_digits=18)),
                ('market_price', models.DecimalField(decimal_places=2, default=1, max_digits=18)),
                ('trade_floor', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('trade_ceiling', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('crypto_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('time_duration_choice', models.IntegerField(choices=[(5, '5 minutes'), (15, '15 minutes'), (30, '30 minutes'), (60, '1 hour'), (300, '5 hours'), (720, '12 hours'), (1440, '1 day')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rampp2p.Ad')),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rampp2p.CryptoCurrency')),
                ('fiat_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rampp2p.FiatCurrency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rampp2p.Peer')),
                ('payment_methods', models.ManyToManyField(related_name='ad_snapshots', to='rampp2p.PaymentMethod')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='ad',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='rampp2p.AdSnapshot'),
        ),
    ]
