# Generated by Django 3.0.14 on 2023-09-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0069_auto_20230908_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ad',
            new_name='ad_snapshot',
        ),
    ]
