# Generated by Django 3.0.14 on 2023-09-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0070_auto_20230908_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsnapshot',
            name='owner',
        ),
    ]
