# Generated by Django 3.0.14 on 2023-09-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0071_remove_adsnapshot_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbiter',
            name='is_disabled',
            field=models.BooleanField(default=True),
        ),
    ]
