# Generated by Django 3.0.14 on 2023-09-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0072_auto_20230919_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='amount',
            new_name='value',
        ),
    ]
