# Generated by Django 3.0.14 on 2023-09-27 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0073_auto_20230922_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsnapshot',
            old_name='crypto_amount',
            new_name='max_trade_amount',
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='rampp2p.Ad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ad_snapshot',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='rampp2p.AdSnapshot'),
        ),
    ]
