# Generated by Django 3.0.14 on 2023-09-27 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0074_auto_20230927_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ad_snapshot',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='rampp2p.AdSnapshot'),
        ),
    ]
