# Generated by Django 3.0.14 on 2023-09-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0075_auto_20230927_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='crypto_amount',
            new_name='trade_amount',
        ),
        migrations.RenameField(
            model_name='adsnapshot',
            old_name='max_trade_amount',
            new_name='trade_amount',
        ),
    ]
