# Generated by Django 3.0.14 on 2023-09-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0076_auto_20230927_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='trade_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='trade_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
