# Generated by Django 3.0.14 on 2023-09-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0077_auto_20230927_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
