# Generated by Django 3.0.14 on 2023-09-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0078_ad_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_methods',
            field=models.ManyToManyField(null=True, to='rampp2p.PaymentMethod'),
        ),
    ]
