# Generated by Django 3.0.14 on 2023-09-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0079_auto_20230928_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_methods',
            field=models.ManyToManyField(to='rampp2p.PaymentMethod'),
        ),
    ]
