# Generated by Django 3.0.14 on 2023-10-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0080_auto_20230928_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='fixed_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ad',
            name='floating_price',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ad',
            name='trade_ceiling',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ad',
            name='trade_floor',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='fixed_price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='floating_price',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='market_price',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='trade_ceiling',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='trade_floor',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
