# Generated by Django 3.0.14 on 2023-10-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0082_auto_20231002_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='auth_nonce',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='peer',
            name='auth_token',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
