# Generated by Django 3.0.14 on 2023-10-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0083_auto_20231005_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='auth_token',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
