# Generated by Django 3.0.14 on 2023-10-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0084_auto_20231006_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='auth_token',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
