# Generated by Django 3.0.14 on 2023-10-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0085_auto_20231006_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='is_deleted',
        ),
    ]
