# Generated by Django 3.0.14 on 2023-10-11 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0086_remove_ad_is_deleted'),
        ('rampp2p', '0083_auto_20231009_0339'),
    ]

    operations = [
    ]
