# Generated by Django 3.0.14 on 2023-10-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0087_merge_20231011_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbiter',
            name='auth_nonce',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='arbiter',
            name='auth_token',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
