# Generated by Django 3.0.14 on 2023-10-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0088_auto_20231011_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='auth_nonce',
        ),
        migrations.RemoveField(
            model_name='peer',
            name='auth_token',
        ),
    ]
