# Generated by Django 3.0.14 on 2023-10-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0090_auto_20231017_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbiter',
            name='auth_nonce',
        ),
        migrations.RemoveField(
            model_name='arbiter',
            name='auth_token',
        ),
    ]
