# Generated by Django 3.0.14 on 2023-10-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0091_auto_20231017_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
