# Generated by Django 3.0.14 on 2023-11-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0092_auto_20231025_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='trade_ceiling',
        ),
        migrations.RemoveField(
            model_name='adsnapshot',
            name='trade_ceiling',
        ),
    ]
