# Generated by Django 3.0.14 on 2023-12-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0094_auto_20231107_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
