# Generated by Django 3.0.14 on 2024-01-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0095_order_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbiter',
            name='chat_identity_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peer',
            name='chat_identity_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
