# Generated by Django 3.0.14 on 2024-01-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0100_auto_20240119_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='format',
            field=models.CharField(max_length=100),
        ),
    ]
