# Generated by Django 3.0.14 on 2024-01-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0101_auto_20240119_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='account_number',
            new_name='account_identifier',
        ),
    ]
