# Generated by Django 3.0.14 on 2024-01-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0102_auto_20240119_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='payment_methods',
            field=models.ManyToManyField(db_index=True, related_name='ads', to='rampp2p.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='trade_type',
            field=models.CharField(choices=[('SELL', 'Sell'), ('BUY', 'Buy')], db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='payment_methods',
            field=models.ManyToManyField(db_index=True, related_name='ad_snapshots', to='rampp2p.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='trade_type',
            field=models.CharField(choices=[('SELL', 'Sell'), ('BUY', 'Buy')], db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='arbiter',
            name='wallet_hash',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_methods',
            field=models.ManyToManyField(db_index=True, to='rampp2p.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='peer',
            name='wallet_hash',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('SBM', 'Submitted'), ('CNF', 'Confirmed'), ('ESCRW_PN', 'Escrow Pending'), ('ESCRW', 'Escrowed'), ('PD_PN', 'Paid Pending'), ('PD', 'Paid'), ('APL', 'Appealed'), ('RLS_PN', 'Release Pending'), ('RLS', 'Released'), ('RFN_PN', 'Refund Pending'), ('RFN', 'Refunded'), ('CNCL', 'Canceled')], db_index=True, max_length=10),
        ),
    ]
