# Generated by Django 3.0.14 on 2024-01-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0103_auto_20240122_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='payment_methods',
            field=models.ManyToManyField(related_name='ads', to='rampp2p.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='payment_methods',
            field=models.ManyToManyField(related_name='ad_snapshots', to='rampp2p.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='price_type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('FLOATING', 'Floating')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='type',
            field=models.CharField(choices=[('RLS', 'Release'), ('RFN', 'Refund')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_methods',
            field=models.ManyToManyField(to='rampp2p.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('ESCROW', 'Escrow'), ('REFUND', 'Refund'), ('RELEASE', 'Release')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
