# Generated by Django 3.0.14 on 2024-01-26 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0104_auto_20240122_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_ref_id', models.IntegerField()),
                ('member_type', models.CharField(choices=[('PEER', 'Peer'), ('ARBITER', 'Arbiter')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('pubkey', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rampp2p.Contract')),
            ],
            options={
                'unique_together': {('contract', 'member_ref_id')},
            },
        ),
    ]
