# Generated by Django 3.0.14 on 2024-01-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0106_auto_20240126_0548'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractmember',
            unique_together={('contract', 'member_ref_id', 'member_type')},
        ),
    ]
