# Generated by Django 3.0.14 on 2024-01-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0107_auto_20240126_0614'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractmember',
            unique_together={('contract', 'member_type')},
        ),
    ]
