# Generated by Django 3.0.14 on 2024-01-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0108_auto_20240126_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='default_fiat',
        ),
        migrations.AddField(
            model_name='arbiter',
            name='address_path',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contractmember',
            name='address_path',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='peer',
            name='address_path',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='arbiter',
            name='address',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='arbiter',
            name='public_key',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='arbiter',
            name='wallet_hash',
            field=models.CharField(db_index=True, max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='contractmember',
            name='address',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='contractmember',
            name='pubkey',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='peer',
            name='address',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='peer',
            name='public_key',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='peer',
            name='wallet_hash',
            field=models.CharField(db_index=True, max_length=75, unique=True),
        ),
    ]
