# Generated by Django 3.0.14 on 2024-02-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0109_auto_20240129_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='time_duration_choice',
            new_name='appeal_cooldown_choice',
        ),
        migrations.RenameField(
            model_name='adsnapshot',
            old_name='time_duration_choice',
            new_name='appeal_cooldown_choice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='expires_at',
            new_name='appealable_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='crypto_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fiat_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_duration_choice',
        ),
    ]
