# Generated by Django 3.0.14 on 2024-02-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0110_auto_20240201_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='version',
            field=models.CharField(default='0.7.5', max_length=100),
        ),
    ]
