# Generated by Django 3.0.14 on 2024-02-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0111_contract_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='version',
            field=models.CharField(default='', max_length=100),
        ),
    ]
