# Generated by Django 3.0.14 on 2024-03-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0113_auto_20240304_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='address_type',
        ),
    ]
