# Generated by Django 3.0.14 on 2024-03-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0114_remove_contract_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='appeal_cooldown_choice',
            field=models.IntegerField(choices=[(5, '5 minutes'), (15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes')]),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='appeal_cooldown_choice',
            field=models.IntegerField(choices=[(5, '5 minutes'), (15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes')]),
        ),
    ]
