# Generated by Django 3.0.14 on 2024-03-12 05:27

from django.db import migrations

def update_appeal_choices(apps, schema_editor):
    Ad = apps.get_model('rampp2p', 'Ad')
    Ad.objects.filter(appeal_cooldown_choice__in=[5, 300, 720, 1440]).update(appeal_cooldown_choice=60)

class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0117_auto_20240312_0526'),
    ]

    operations = [
        migrations.RunPython(update_appeal_choices)
    ]
