# Generated by Django 3.0.14 on 2024-03-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0118_auto_20240312_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketrate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
