# Generated by Django 3.0.14 on 2024-03-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0119_auto_20240314_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
