# Generated by Django 3.0.14 on 2024-03-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0121_reservedname'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedname',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rampp2p.Peer'),
        ),
        migrations.AlterField(
            model_name='peer',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='reservedname',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
