# Generated by Django 3.0.14 on 2024-03-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0126_auto_20240318_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTypeFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(db_index=True, max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='format',
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='format',
            field=models.ManyToManyField(to='rampp2p.PaymentTypeFormat'),
        ),
    ]
