# Generated by Django 3.0.14 on 2024-03-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0127_auto_20240318_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
