# Generated by Django 3.0.14 on 2024-03-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0129_auto_20240318_0628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='format',
            new_name='formats',
        ),
    ]
