# Generated by Django 3.0.14 on 2024-03-19 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0130_auto_20240318_0648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentTypeFormat',
            new_name='IdentifierFormat',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='identifier_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rampp2p.IdentifierFormat'),
        ),
    ]
