# Generated by Django 3.0.14 on 2024-03-19 04:29

from django.db import migrations

def update_payment_methods(apps, schema_editor):
    IdentifierFormat = apps.get_model('rampp2p', 'IdentifierFormat')
    PaymentMethod = apps.get_model('rampp2p', 'PaymentMethod')
    payment_methods = PaymentMethod.objects.filter(identifier_format__isnull=True)

    email_format = IdentifierFormat.objects.filter(format='Email Address').first()
    mobilenum_format = IdentifierFormat.objects.filter(format='Mobile Number').first()
    string_format = IdentifierFormat.objects.filter(format='Alphanumeric String').first()
    for method in payment_methods:
        paymenttype = method.payment_type.name 
        if paymenttype == 'Gcash' or paymenttype == 'Maya':
            method.identifier_format=mobilenum_format
        elif paymenttype == 'Paypal':
            method.identifier_format=email_format
        else:
            method.identifier_format=string_format
        method.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0131_auto_20240319_0424'),
    ]

    operations = [
        migrations.RunPython(update_payment_methods)
    ]
