# Generated by Django 3.0.14 on 2024-03-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0132_auto_20240319_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifierformat',
            name='format',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
