# Generated by Django 3.0.14 on 2024-03-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0133_auto_20240319_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
