# Generated by Django 3.0.14 on 2024-03-25 06:48

from django.db import migrations

def update_ad_payment_methods(apps, schema_editor):
    # Check all undeleted ads, remove payment methods that are unsupported by the ad's fiat currency
    Ad = apps.get_model('rampp2p', 'Ad')
    ads = Ad.objects.filter(deleted_at__isnull=True)
    for ad in ads:
        # get the ids of the payment types allowed for the ad's currency
        currency_paymenttypes = ad.fiat_currency.payment_types.values_list('id', flat=True)
        # get the payment methods of the ad
        ad_payment_methods = ad.payment_methods.all()
        
        # check if each of the ad's payment method belong to currency's allowed payment types
        for payment_method in ad_payment_methods:
            if not (payment_method.payment_type.id in currency_paymenttypes):
                # remove ad payment method if it's not in the currency's allowed payment types
                ad.payment_methods.remove(payment_method)

class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0134_paymenttype_notes'),
    ]

    operations = [
        migrations.RunPython(update_ad_payment_methods)
    ]
