# Generated by Django 3.0.14 on 2024-04-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0135_auto_20240325_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chat_session_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
