# Generated by Django 3.0.14 on 2024-04-16 02:58

from django.db import migrations
from django.db.models import OuterRef, Subquery
from rampp2p.models import StatusType
from datetime import timedelta

def init_empty_order_expires_at(apps, schema_editor):
    Order = apps.get_model('rampp2p', 'Order')
    Status = apps.get_model('rampp2p', 'Status')
    # subquery to find the order with status SUBMITTED
    last_status = Status.objects.filter(
        order=OuterRef('pk'),
        status__in=[StatusType.SUBMITTED]
    ).order_by('-created_at').values('order')[:1]
    # fetch SUBMITTED orders with expires_at = null
    submitted_orders = Order.objects.filter(pk__in=Subquery(last_status))
    submitted_orders = submitted_orders.filter(expires_at__isnull=True)
    # initialize the expiration date of these orders
    for order in submitted_orders:
        order.expires_at = order.created_at + timedelta(hours=24)
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0139_order_expires_at'),
    ]

    operations = [
        migrations.RunPython(init_empty_order_expires_at)
    ]
