# Generated by Django 3.0.14 on 2024-04-29 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0141_delete_duplicate_cancelled_status_20240422_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rampp2p.Order')),
                ('peer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_members', to='rampp2p.Peer')),
            ],
        ),
    ]
