# Generated by Django 3.0.14 on 2024-04-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0142_ordermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermember',
            name='arbiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_members', to='rampp2p.Arbiter'),
        ),
        migrations.AddField(
            model_name='ordermember',
            name='type',
            field=models.CharField(choices=[('SELLER', 'Seller'), ('BUYER', 'Buyer'), ('ARBITER', 'Arbiter')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordermember',
            name='peer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_members', to='rampp2p.Peer'),
        ),
        migrations.AlterUniqueTogether(
            name='ordermember',
            unique_together={('type', 'order')},
        ),
    ]
