# Generated by Django 3.0.14 on 2024-04-29 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0143_auto_20240429_0510'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordermember',
            unique_together={('type', 'peer')},
        ),
    ]
