# Generated by Django 3.0.14 on 2024-05-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0147_init_completed_order_members_20240430_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='account_name_required',
            field=models.BooleanField(default=False),
        ),
    ]
