# Generated by Django 3.0.14 on 2024-05-03 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0148_paymenttype_account_name_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='account_name_required',
            new_name='acc_name_req',
        ),
    ]
