# Generated by Django 3.0.14 on 2024-05-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0150_auto_20240508_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttype',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='short_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
