# Generated by Django 3.0.14 on 2024-05-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0153_auto_20240509_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='trade_amount_in_fiat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ad',
            name='trade_limits_in_fiat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adsnapshot',
            name='trade_amount_in_fiat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adsnapshot',
            name='trade_limits_in_fiat',
            field=models.BooleanField(default=False),
        ),
    ]
