# Generated by Django 3.0.14 on 2024-05-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0154_auto_20240521_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbiter',
            name='fiat_currencies',
            field=models.ManyToManyField(to='rampp2p.FiatCurrency'),
        ),
    ]
