# Generated by Django 3.0.14 on 2024-06-05 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0155_arbiter_fiat_currencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rampp2p.Order')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rampp2p.PaymentMethod')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rampp2p.PaymentType')),
            ],
        ),
    ]
