# Generated by Django 3.0.14 on 2024-06-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0156_orderpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbiter',
            name='pause_until',
            field=models.DateTimeField(null=True),
        ),
    ]
