# Generated by Django 3.0.14 on 2024-06-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0157_arbiter_pause_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbiter',
            old_name='pause_until',
            new_name='unavailable_until',
        ),
    ]
