# Generated by Django 3.0.14 on 2024-06-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0158_auto_20240606_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbiter',
            old_name='unavailable_until',
            new_name='inactive_until',
        ),
    ]
