# Generated by Django 3.0.14 on 2024-06-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0159_auto_20240607_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiatcurrency',
            options={'ordering': ['name', 'symbol']},
        ),
    ]
