# Generated by Django 3.0.14 on 2024-06-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0161_arbiter_read_completed_orders_20240611_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketrate',
            options={'ordering': ['currency']},
        ),
    ]
