# Generated by Django 3.0.14 on 2024-06-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0162_auto_20240613_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbiter',
            name='fiat_currencies',
            field=models.ManyToManyField(blank=True, to='rampp2p.FiatCurrency'),
        ),
        migrations.AlterField(
            model_name='arbiter',
            name='inactive_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
