# Generated by Django 3.0.14 on 2024-06-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0164_auto_20240618_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_appeals', to='rampp2p.Order'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_appeals', to='rampp2p.Peer'),
        ),
    ]
