# Generated by Django 3.0.14 on 2024-07-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0165_auto_20240619_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTypeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=100)),
                ('format', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('required', models.BooleanField(default=True)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='rampp2p.PaymentType')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('field_reference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='rampp2p.PaymentTypeField')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='rampp2p.PaymentMethod')),
            ],
        ),
    ]
