# Generated by Django 3.0.14 on 2024-07-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0169_init_paymentmethod_fields_20240719_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='account_identifier',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='identifier_format',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='acc_name_required',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='formats',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='has_qr_code',
        ),
    ]
