# Generated by Django 3.0.14 on 2024-07-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0171_auto_20240722_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cash_in',
            field=models.BooleanField(default=False),
        ),
    ]
