# Generated by Django 3.0.14 on 2024-07-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0173_read_auto_canceled_orders_20240724_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
