# Generated by Django 3.0.14 on 2024-07-31 05:28

from django.db import migrations

import logging
logger = logging.getLogger(__name__)

def set_order_tracking_id(apps, schema_editor):
    Order = apps.get_model('rampp2p', 'Order')

    # find orders with no tracking_id
    orders = Order.objects.filter(tracking_id__isnull=True).order_by('created_at')
    order_counter = 0
    date = None
    for order in orders:
        created_at_date = order.created_at.date()
        if created_at_date != date:
            date = created_at_date
            order_counter = 0
        order_counter += 1
        tracking_id = f'PEO{date.year}{str(date.month).zfill(2)}{str(date.day).zfill(2)}-{str(order_counter).zfill(4)}'
        logger.warn(f'tracking_id: {tracking_id}')
        order.tracking_id = tracking_id
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0174_auto_20240731_0434'),
    ]

    operations = [
        migrations.RunPython(set_order_tracking_id)
    ]
