# Generated by Django 3.0.14 on 2024-07-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0175_set_order_tracking_id_20240731_0528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderManager',
        ),
    ]
