# Generated by Django 3.0.14 on 2024-07-31 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0176_delete_ordermanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPaymentTypeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=100)),
                ('model_ref', models.CharField(choices=[('Order', 'Order')], db_index=True, max_length=5)),
                ('field_ref', models.CharField(choices=[('id', 'Id'), ('tracking_id', 'Tracking Id')], db_index=True, max_length=50)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='rampp2p.PaymentType')),
            ],
        ),
    ]
