# Generated by Django 3.0.14 on 2024-07-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0177_dynamicpaymenttypefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpaymenttypefield',
            name='model_ref',
            field=models.CharField(choices=[('order', 'Order')], db_index=True, max_length=5),
        ),
    ]
