# Generated by Django 3.0.14 on 2024-08-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0179_auto_20240815_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='is_cashin_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peer',
            name='is_cashin_whitelisted',
            field=models.BooleanField(default=False),
        ),
    ]
