# Generated by Django 3.0.14 on 2024-08-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0181_auto_20240822_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatcurrency',
            name='cashin_blacklist',
            field=models.ManyToManyField(blank=True, related_name='cashin_currency_blacklist', to='rampp2p.Peer'),
        ),
        migrations.AlterField(
            model_name='fiatcurrency',
            name='cashin_whitelist',
            field=models.ManyToManyField(blank=True, related_name='cashin_currency_whitelist', to='rampp2p.Peer'),
        ),
    ]
