# Generated by Django 3.0.14 on 2024-09-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0183_read_canceled_orders_20240828_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatcurrency',
            name='payment_types',
            field=models.ManyToManyField(related_name='payment_currency', to='rampp2p.PaymentType'),
        ),
    ]
