# Generated by Django 3.0.14 on 2024-09-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0183_read_canceled_orders_20240828_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=10)),
                ('latest_version', models.CharField(max_length=10)),
                ('min_required_version', models.CharField(max_length=10)),
                ('release_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
