# Generated by Django 3.0.14 on 2024-09-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0184_appversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10),
        ),
    ]
