# Generated by Django 3.0.14 on 2024-09-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0185_auto_20240916_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='platform',
            field=models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10),
        ),
    ]
