# Generated by Django 3.0.14 on 2024-09-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0184_auto_20240918_0749'),
        ('rampp2p', '0186_auto_20240916_0722'),
    ]

    operations = [
    ]
