# Generated by Django 3.0.14 on 2024-09-27 05:15

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0187_merge_20240923_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('ad_summary', 'Ad Summary'), ('ad_update', 'Ad Update'), ('order_summary', 'Order Summary'), ('order_status_update', 'Order Status Update'), ('appeal_summary', 'Appeal Summary'), ('appeal_update', 'Appeal Update')], max_length=50)),
                ('object_id', models.BigIntegerField()),
                ('metadata', jsonfield.fields.JSONField(blank=True, help_text='Arbitrary data to add context to the message', null=True)),
                ('channel', models.CharField(max_length=50)),
                ('ts', models.DecimalField(decimal_places=6, max_digits=18)),
                ('thread_ts', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('permalink', models.URLField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
