# Generated by Django 3.0.14 on 2024-09-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0188_auto_20240923_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='buyer_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='seller_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
