# Generated by Django 3.0.14 on 2024-10-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0190_read_order_statuses_20240925_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatcurrency',
            name='cashin_presets',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
