# Generated by Django 3.0.14 on 2024-10-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0191_fiatcurrency_cashin_presets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatcurrency',
            name='payment_types',
            field=models.ManyToManyField(blank=True, related_name='payment_currency', to='rampp2p.PaymentType'),
        ),
    ]
