# Generated by Django 3.0.14 on 2024-10-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0193_cryptocurrency_cashin_presets'),
        ('rampp2p', '0188_slackmessagelog'),
    ]

    operations = [
    ]
