# Generated by Django 3.0.14 on 2024-11-19 09:19

from django.db import migrations

def add_p2p_exchange_req_version(apps, schema_editor):
    AppVersion = apps.get_model('rampp2p', 'AppVersion')
    platforms = ['ios', 'android', 'web']
    release_notes = "- Improvements in cash-in UI/UX\n- Multiple improvements and bug fixes in P2P Exchange"
    for platform in platforms:
        AppVersion.objects.create(
            platform=platform, 
            latest_version='0.20.1', 
            min_required_version='0.20.1',
            notes=release_notes)

class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0195_mark_excess_ads_private_20241112_0053'),
    ]

    operations = [
        migrations.RunPython(add_p2p_exchange_req_version)
    ]
