# Generated by Django 3.0.14 on 2024-11-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0195_mark_excess_ads_private_20241112_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_appeals', to='rampp2p.Order'),
        ),
    ]
