# Generated by Django 3.0.14 on 2024-11-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0195_servicefee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefee',
            name='type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('FLOATING', 'Floating')], default='FLOATING', max_length=8),
        ),
    ]
