# Generated by Django 3.0.14 on 2024-11-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0196_auto_20241113_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefee',
            name='fixed_value',
            field=models.DecimalField(blank=True, decimal_places=8, default=1000, max_digits=18),
        ),
    ]
