# Generated by Django 3.0.14 on 2024-11-20 01:53

from django.db import migrations

def add_app_min_required_versions(apps, schema_editor):
    MainAppVersion = apps.get_model('main', 'AppVersion')
    P2PExchangeAppVersion = apps.get_model('rampp2p', 'AppVersion')
    platforms = ['ios', 'android', 'web']
    main_release_notes = "Release notes\n- Added notifications icon and display page\n- Added support for bch-wif prefix sweeping funds from private keys\n- Support for cashback in marketplace purchases\n- Improvements in cash-in UI/UX\n- Improvements in setting amount in BCH receive page\n- Multiple improvements and bug fixes in P2P Exchange\n- Fix of styling and UI issues in browser extension"
    p2p_exchange_release_notes = "- Improvements in cash-in UI/UX\n- Multiple improvements and bug fixes in P2P Exchange"
    for platform in platforms:
        MainAppVersion.objects.create(
            platform=platform, 
            latest_version='0.20.1', 
            min_required_version='0.20.1',
            notes=main_release_notes)
        P2PExchangeAppVersion.objects.create(
            platform=platform, 
            latest_version='0.20.1', 
            min_required_version='0.20.1',
            notes=p2p_exchange_release_notes)

class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0196_auto_20241120_0138'),
    ]

    operations = [
        migrations.RunPython(add_app_min_required_versions)
    ]
