# Generated by Django 3.0.14 on 2024-11-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0197_auto_20241114_0308'),
        ('rampp2p', '0195_mark_excess_ads_private_20241112_0053'),
    ]

    operations = [
    ]
