# Generated by Django 3.0.14 on 2024-12-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0198_auto_20241129_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatcurrency',
            name='payment_types',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='payment_currency', to='rampp2p.PaymentType'),
        ),
    ]
