# Generated by Django 3.0.14 on 2024-11-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0198_merge_20241114_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='arbitration_fee',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='hardcoded_fee',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='service_fee',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='servicefee',
            name='fixed_value',
            field=models.IntegerField(blank=True, default=1000),
        ),
    ]
