# Generated by Django 3.0.14 on 2024-11-14 10:01

# Generated by Django 3.0.14 on 2024-11-14 08:15

from django.db import migrations
from django.conf import settings

import logging
logger = logging.getLogger(__name__)

def init_empty_contract_fees(apps, schema_editor):
    Contract = apps.get_model('rampp2p', 'Contract')
    contracts = Contract.objects.all()
    logger.info(f'Found {contracts.count}')

    for contract in contracts:
        logger.info(f'Initializing Contract #{contract.id} | hardcoded_fee: {settings.HARDCODED_FEE} | arbitration_fee: {settings.ARBITRATION_FEE} | service_fee: {settings.SERVICE_FEE}')
        contract.hardcoded_fee = int(settings.HARDCODED_FEE)
        contract.arbitration_fee = int(settings.ARBITRATION_FEE)
        contract.service_fee = int(settings.SERVICE_FEE)
        contract.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0199_auto_20241114_0955'),
    ]

    operations = [
        migrations.RunPython(init_empty_contract_fees)
    ]
