# Generated by Django 3.0.14 on 2024-11-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0200_auto_20241115_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='hardcoded_fee',
            new_name='contract_fee',
        )
    ]
