# Generated by Django 3.0.14 on 2024-11-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0202_init_empty_contract_fees_20241115_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Arbitration Fee', 'Arbitration'), ('Service Fee', 'Service')], max_length=30, unique=True)),
                ('type', models.CharField(choices=[('FIXED', 'Fixed'), ('FLOATING', 'Floating')], default='FLOATING', max_length=8)),
                ('fixed_value', models.IntegerField(blank=True, default=1000)),
                ('floating_value', models.DecimalField(blank=True, decimal_places=8, default=0.5, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceFee',
        ),
    ]
