# Generated by Django 3.0.14 on 2024-11-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0203_auto_20241118_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradefee',
            name='type',
            field=models.CharField(choices=[('FIXED', 'Fixed'), ('FLOATING', 'Floating')], default='FIXED', max_length=8),
        ),
    ]
