# Generated by Django 3.0.14 on 2024-11-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0204_auto_20241118_0856'),
        ('rampp2p', '0196_auto_20241118_0811'),
    ]

    operations = [
    ]
