# Generated by Django 3.0.14 on 2024-11-21 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0205_merge_20241120_0632'),
        ('rampp2p', '0197_add_app_min_required_versions_20241120_0153'),
    ]

    operations = [
    ]
