# Generated by Django 3.0.14 on 2024-11-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0206_merge_20241121_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='trade_amount_sats',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='trade_ceiling_sats',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='trade_floor_sats',
            field=models.BigIntegerField(null=True),
        ),
    ]
