# Generated by Django 3.0.14 on 2024-11-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0208_init_ad_trade_limits_sats_20241122_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsnapshot',
            name='trade_amount_sats',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adsnapshot',
            name='trade_ceiling_sats',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adsnapshot',
            name='trade_floor_sats',
            field=models.BigIntegerField(null=True),
        ),
    ]
