# Generated by Django 3.0.14 on 2024-11-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0210_init_ad_snapshot_trade_limit_sats_20241122_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='trade_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
