# Generated by Django 3.0.14 on 2024-11-22 07:28

from django.db import migrations
from rampp2p.utils import bch_to_satoshi
import logging
logger = logging.getLogger(__name__)

def init_order_trade_amount(apps, schema_editor):
    Order = apps.get_model('rampp2p', 'Order')
    orders = Order.objects.filter(trade_amount__isnull=True)

    for order in orders:
        order.trade_amount = bch_to_satoshi(order.crypto_amount)
        order.save()

        logger.info(f'Order #{order.id} | crypto_amount: {order.crypto_amount} | trade_amount: {order.trade_amount}')

class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0211_auto_20241122_0727'),
    ]

    operations = [
        migrations.RunPython(init_order_trade_amount)
    ]
