# Generated by Django 3.0.14 on 2024-11-25 09:59

from django.db import migrations
from django.db.models import Q

def init_empty_trade_limit_fiat(apps, schema_editor):
    Ad = apps.get_model('rampp2p', 'Ad')
    ads = Ad.objects.filter(Q(deleted_at__isnull=True) & (Q(trade_amount_in_fiat=True) | Q(trade_limits_in_fiat=True)))

    for ad in ads:
        if ad.trade_amount_in_fiat and ad.trade_amount_fiat == 0:
            ad.trade_amount_fiat = ad.trade_amount
        if ad.trade_limits_in_fiat:
            if ad.trade_floor_fiat == 0:
                ad.trade_floor_fiat = ad.trade_floor
            if ad.trade_ceiling_fiat == 0:
                ad.trade_ceiling_fiat = ad.trade_ceiling
        ad.save()

    AdSnapshot = apps.get_model('rampp2p', 'AdSnapshot')
    snapshots = AdSnapshot.objects.filter(Q(trade_amount_in_fiat=True) | Q(trade_limits_in_fiat=True))

    for snapshot in snapshots:
        if snapshot.trade_amount_in_fiat and snapshot.trade_amount_fiat == 0:
            snapshot.trade_amount_fiat = snapshot.trade_amount
        if snapshot.trade_limits_in_fiat:
            if snapshot.trade_floor_fiat == 0:
                snapshot.trade_floor_fiat = snapshot.trade_floor
            if snapshot.trade_ceiling_fiat == 0:
                snapshot.trade_ceiling_fiat = snapshot.trade_ceiling
        snapshot.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0216_auto_20241125_0959'),
    ]

    operations = [
        migrations.RunPython(init_empty_trade_limit_fiat)
    ]
