# Generated by Django 3.0.14 on 2024-11-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0218_trade_amount_in_fiat_if_trade_limits_in_fiat_20241125_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='trade_amount_fiat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ad',
            name='trade_ceiling_fiat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ad',
            name='trade_floor_fiat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='trade_amount_fiat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='trade_ceiling_fiat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='adsnapshot',
            name='trade_floor_fiat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
