# Generated by Django 3.0.14 on 2024-11-26 08:44

from django.db import migrations
from django.db.models import Q
from rampp2p.models import PriceType
from rampp2p.utils import bch_to_fiat, satoshi_to_bch

import logging
logger = logging.getLogger(__name__)

def get_price(ad):
    if ad.price_type == PriceType.FIXED:
        return ad.fixed_price
    return ad.market_price * (ad.floating_price/100)

def snapshot_trade_amount_in_fiat_if_trade_limits_in_fiat(apps, schema_editor):
    AdSnapshot = apps.get_model('rampp2p', 'AdSnapshot')
    ads = AdSnapshot.objects.filter(Q(trade_limits_in_fiat=True) & Q(trade_amount_in_fiat=False))

    for ad in ads:
        if ad.trade_amount_sats:
            ad.trade_amount_in_fiat = True
            ad.trade_amount_fiat = bch_to_fiat(satoshi_to_bch(ad.trade_amount_sats), get_price(ad))
            ad.save()

            logger.warning(f'Updated AdSnapshot#{ad.id} | trade_amount_fiat: {ad.trade_amount_fiat}')

class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0219_auto_20241126_0619'),
    ]

    operations = [
        migrations.RunPython(snapshot_trade_amount_in_fiat_if_trade_limits_in_fiat)
    ]
