# Generated by Django 3.0.14 on 2024-11-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0221_min_required_version_0_20_2_20241126_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created_by',
            field=models.CharField(blank=True, db_index=True, max_length=75, null=True),
        ),
    ]
