# Generated by Django 3.0.14 on 2024-12-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0222_status_created_by'),
        ('rampp2p', '0198_auto_20241129_0838'),
    ]

    operations = [
    ]
