# Generated by Django 3.0.14 on 2024-12-03 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0224_featuretoggle'),
        ('rampp2p', '0199_auto_20241202_0154'),
    ]

    operations = [
    ]
