# Generated by Django 3.0.14 on 2024-12-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0225_merge_20241203_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretoggle',
            name='feature_name',
            field=models.CharField(choices=[('AdShareLink', 'Adsharelink'), ('CreateOrders', 'Createorders'), ('CashIn', 'Cashin')], max_length=100, unique=True),
        ),
    ]
