# Generated by Django 3.0.14 on 2024-12-18 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0226_auto_20241209_0411'),
        ('rampp2p', '0226_auto_20241211_0544'),
    ]

    operations = [
    ]
