# Generated by Django 3.0.14 on 2025-01-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0227_merge_20241218_0225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureToggle',
        ),
    ]
