# Generated by Django 3.0.14 on 2025-01-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0228_auto_20250107_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AD_SHARE_LINKS', 'Ad Share Links'), ('ORDER_CREATE', 'Order Create'), ('ORDER_ESCROW', 'Order Escrow'), ('AD_CREATE', 'Ad Create'), ('AD_UPDATE', 'Ad Update')], max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
