# Generated by Django 3.0.14 on 2025-07-30 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0230_auto_20250120_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='rampp2p.Order'),
        ),
    ]
