# Generated by Django 3.0.14 on 2025-07-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0231_auto_20250730_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
