# Generated by Django 3.0.14 on 2025-10-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0232_ad_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
