# Generated by Django 3.0.14 on 2026-05-26 03:00

from django.db import migrations, models
from django.utils import timezone
from datetime import timedelta

def backfill_ad_expires_at(apps, schema_editor):
    Ad = apps.get_model('rampp2p', 'Ad')
    now = timezone.now()
    # Give all existing non-deleted ads a 30-day window from now so they
    # remain visible immediately after the migration runs. Using
    # `max(created_at + 30d, now)` caused ads older than 30 days to receive
    # an expires_at equal to the migration run time, making them expire
    # instantly and disappear from all listings.
    Ad.objects.filter(deleted_at__isnull=True, expires_at__isnull=True).update(
        expires_at=now + timedelta(days=30)
    )

class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0233_ad_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['expires_at'], name='rampp2p_ad_expires_at_idx'),
        ),
        migrations.RunPython(backfill_ad_expires_at, reverse_code=migrations.RunPython.noop),
    ]
