# Generated by Django 3.0.14 on 2025-11-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0234_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ad',
            name='rampp2p_ad_trade_limits_in_fiat_idx',
        ),
        migrations.RemoveIndex(
            model_name='ad',
            name='rampp2p_ad_trade_amount_sats_idx',
        ),
        migrations.RemoveIndex(
            model_name='ad',
            name='rampp2p_ad_trade_amount_fiat_idx',
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['trade_limits_in_fiat'], name='rampp2p_ad_trade_limits_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['trade_amount_sats'], name='rampp2p_ad_trade_amt_sats_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['trade_amount_fiat'], name='rampp2p_ad_trade_amt_fiat_idx'),
        ),
    ]
