# Generated by Django 3.0.14 on 2026-04-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0235_auto_20251102_1410'),
        ('rampp2p', '0235_orderpayment_unique_together'),
    ]

    operations = [
    ]
