# Generated by Django 3.0.14 on 2026-05-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0236_merge_20260414_0925'),
        ('rampp2p', '0234_ad_expires_at'),
    ]

    operations = [
    ]
