# Generated by Django 3.0.14 on 2026-06-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0237_merge_20260526_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_peer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reports_received',
                    to='rampp2p.Peer',
                )),
                ('reporter', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='filed_reports',
                    to='rampp2p.Peer',
                )),
            ],
            options={
                'unique_together': {('reporter', 'reported_peer')},
            },
        ),
    ]
