# Generated by Django 3.0.14 on 2023-10-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_hash', models.CharField(max_length=100)),
                ('nonce', models.CharField(max_length=6)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nonce_expires_at', models.DateTimeField()),
                ('key_expires_at', models.DateTimeField()),
            ],
        ),
    ]
