# Generated by Django 3.0.14 on 2023-10-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20231013_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='nonce',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
