# Generated by Django 3.0.14 on 2024-10-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20231013_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='nonce',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='nonce_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
