# Generated by Django 3.0.14 on 2023-03-14 08:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_hash', models.CharField(max_length=100)),
                ('bch_address', models.CharField(max_length=100)),
                ('ramp_type', models.CharField(max_length=20)),
                ('shift_id', models.CharField(max_length=50)),
                ('quote_id', models.CharField(max_length=50)),
                ('date_shift_created', models.DateTimeField(blank=True, null=True)),
                ('date_shift_completed', models.DateTimeField(blank=True, null=True)),
                ('shift_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('shift_status', models.CharField(default='waiting', max_length=50)),
            ],
        ),
    ]
