# Generated by Django 3.0.14 on 2022-03-18 01:05

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.DecimalField(decimal_places=0, max_digits=78)),
                ('transactions_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='TokenContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=64)),
                ('token_type', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(db_index=True, max_length=70)),
                ('to_addr', models.CharField(max_length=64)),
                ('from_addr', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=18, max_digits=36)),
                ('data', models.TextField(blank=True, null=True)),
                ('gas', models.IntegerField()),
                ('gas_price', models.IntegerField()),
                ('is_mined', models.BooleanField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('processed_transfers', models.BooleanField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='smartbch.Block')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_index', models.IntegerField(blank=True, null=True)),
                ('to_addr', models.CharField(max_length=64)),
                ('from_addr', models.CharField(max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('token_id', models.IntegerField(blank=True, null=True)),
                ('token_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='smartbch.TokenContract')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='smartbch.Transaction')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
