# Generated by Django 3.0.14 on 2022-03-24 07:17

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20220217_0758'),
        ('smartbch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTransferReceipientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_transfer_logs', to='main.Subscription')),
                ('transaction_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_logs', to='smartbch.TransactionTransfer')),
            ],
            options={
                'unique_together': {('transaction_transfer', 'subscription')},
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
