# Generated by Django 3.0.14 on 2022-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbch', '0003_auto_20220330_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
