# Generated by Django 3.0.14 on 2022-05-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbch', '0007_transaction_gas_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokencontract',
            name='decimals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
