# Generated by Django 3.0.14 on 2022-05-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbch', '0008_tokencontract_decimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokencontract',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='tokencontract',
            name='symbol',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
