# Generated by Django 3.0.14 on 2022-06-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbch', '0009_auto_20220530_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_number',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=78, unique=True),
        ),
    ]
