# Generated by Django 3.0.14 on 2022-07-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartbch', '0010_auto_20220611_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokencontract',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tokencontract',
            name='symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
