version: "3.7"
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure
  bchn:
    image: cagataygurturk/docker-ssh-tunnel
    volumes:
      - /root/.ssh:/root/ssh:ro
    environment:
      SSH_DEBUG: "-v"
      TUNNEL_HOST: bchn-chipnet
      REMOTE_HOST: "${BCHN_CHIPNET_HOST}"
      LOCAL_PORT: 8332
      REMOTE_PORT: 8332
  zmq:
    image: cagataygurturk/docker-ssh-tunnel
    volumes:
      - /root/.ssh:/root/ssh:ro
    environment:
      SSH_DEBUG: "-v"
      TUNNEL_HOST: bchn-chipnet
      REMOTE_HOST: "${BCHN_CHIPNET_HOST}"
      LOCAL_PORT: 28332
      REMOTE_PORT: 28332
  fulcrum:
    image: cagataygurturk/docker-ssh-tunnel
    volumes:
      - /root/.ssh:/root/ssh:ro
    environment:
      SSH_DEBUG: "-v"
      TUNNEL_HOST: bchn-chipnet
      REMOTE_HOST: "${BCHN_CHIPNET_HOST}"
      LOCAL_PORT: 60001
      REMOTE_PORT: 60001
  postgres:
    image: "postgres:11.1-alpine"
    command: -c "max_connections=400"
    volumes:
      - watchtower_db_data:/var/lib/postgresql/data
    env_file:
      - /root/watchtower/compose/.env_chipnet
    expose:
      - "5432"
  redis:
    image: "redis:alpine"
    env_file:
      - /root/watchtower/compose/.env_chipnet
  backend:
    container_name: watchtower_backend
    build: /root/watchtower
    image: watchtower_web
    command: [ "supervisord", "-c", "/code/supervisord.conf", "--nodaemon" ]
    env_file: /root/watchtower/compose/.env_chipnet
    volumes:
      - /var/www/images:/images
      - /code/anyhedge/js/node_modules
      - /code/stablehedge/js/node_modules
    ports:
      - 8000:8000
      - 9000:9000
    depends_on:
      - postgres
      - redis
volumes:
  watchtower_db_data:
    external: true
