version: "3.7"
services:
  docker-host:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure
  web:
    container_name: watchtower_web
    build: /root/watchtower
    image: watchtower_web
    command: [ "supervisord", "-c", "/code/supervisord.conf", "--nodaemon" ]
    env_file: /root/watchtower/compose/.env_mainnet
    volumes:
      - /var/www/images:/images
      - /var/opt/watchtower/media:/code/media
      - /code/anyhedge/js/node_modules
    ports:
      - 8000:8000
      - 9000:9000
