# Generated by Django 3.0.14 on 2026-05-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nostrpubkeydevice',
            name='nostr_pubke_pubkey_116898_idx',
        ),
        migrations.AddIndex(
            model_name='nostrpubkeydevice',
            index=models.Index(fields=['pubkey_hex', 'wallet_hash'], name='nostr_nostr_pubkey__6590fe_idx'),
        ),
    ]