# Generated by Django 3.0.14 on 2026-05-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostr', '0003_refactor_nostr_pubkey'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nostrpubkey',
            name='nostr_nostr_pubkey__6590fe_idx',
        ),
        migrations.AddIndex(
            model_name='nostrpubkey',
            index=models.Index(fields=['pubkey_hex', 'wallet_hash'], name='nostr_nostr_pubkey__046ea9_idx'),
        ),
    ]
