# Generated by Django 3.0.14 on 2023-09-05 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paytacapos', '0011_auto_20230824_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('token_address', models.CharField(max_length=100, unique=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to='paytacapos.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(default='', max_length=100)),
                ('key_category', models.CharField(max_length=100, unique=True)),
                ('lock_category', models.CharField(max_length=100, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='vouchers.Vault')),
            ],
        ),
    ]
