# Generated by Django 3.0.14 on 2023-08-03 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paytacapos', '0008_auto_20230719_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('token_address', models.CharField(max_length=100)),
                ('receiving_pubkey', models.CharField(max_length=60)),
                ('receiving_pubkey_hash', models.CharField(max_length=60)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to='paytacapos.Merchant')),
            ],
        ),
    ]
