# Generated by Django 3.0.14 on 2023-09-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='used',
            new_name='claimed',
        ),
        migrations.AddField(
            model_name='voucher',
            name='claim_txid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='date_claimed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='key_category',
            field=models.CharField(max_length=100),
        ),
    ]
