# Generated by Django 3.0.14 on 2023-08-08 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='merchant_receiving_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='CashdropNftPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_category', models.CharField(max_length=100)),
                ('lock_category', models.CharField(max_length=100)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_credentials', to='vouchers.Vault')),
            ],
        ),
    ]
