# Generated by Django 3.0.14 on 2023-09-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_auto_20230911_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='txid',
            new_name='minting_txid',
        ),
        migrations.AddField(
            model_name='voucher',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
