# Generated by Django 3.0.14 on 2023-09-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_auto_20230911_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='lock_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='key_category',
        ),
    ]
