# Generated by Django 3.0.14 on 2024-03-04 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_voucher_commitment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vault',
            options={'ordering': ('merchant__name',)},
        ),
    ]
