# Generated by Django 3.0.14 on 2023-09-04 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_auto_20230815_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_category', models.CharField(max_length=100, unique=True)),
                ('lock_category', models.CharField(max_length=100, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='vouchers.Vault')),
            ],
        ),
        migrations.DeleteModel(
            name='CashdropNftPair',
        ),
    ]
