# Generated by Django 3.0.14 on 2024-03-25 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_auto_20240227_0856'),
        ('vouchers', '0006_auto_20240304_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='nft',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='main.CashNonFungibleToken'),
        ),
    ]
