# Generated by Django 3.0.14 on 2023-09-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_auto_20230904_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='txid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
