# Generated by Django 3.0.14 on 2024-08-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0026_auto_20240806_0556'),
        ('vouchers', '0007_voucher_nft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vault',
            options={'ordering': ('pos_device__merchant__name',)},
        ),
        migrations.RemoveField(
            model_name='vault',
            name='merchant',
        ),
        migrations.AddField(
            model_name='vault',
            name='pos_device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault', to='paytacapos.PosDevice'),
        ),
    ]
