# Generated by Django 3.0.14 on 2024-08-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_auto_20240806_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='address',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vault',
            name='token_address',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='category',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='claimed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expired',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
