# Generated by Django 3.0.14 on 2024-08-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0009_auto_20240808_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='pubkey',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
    ]
