# Generated by Django 3.0.14 on 2024-09-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0029_auto_20240905_0617'),
        ('vouchers', '0010_vault_pubkey'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vault',
            new_name='PosDeviceVault',
        ),
        migrations.CreateModel(
            name='MerchantVault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=100, unique=True)),
                ('token_address', models.CharField(db_index=True, max_length=100, unique=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to='paytacapos.Merchant')),
            ],
            options={
                'ordering': ('merchant__name',),
            },
        ),
        migrations.AlterField(
            model_name='voucher',
            name='vault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='vouchers.MerchantVault'),
        ),
    ]
