# Generated by Django 3.0.14 on 2024-09-06 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0030_remove_merchant_verification_category'),
        ('vouchers', '0011_auto_20240905_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantvault',
            name='pubkey',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='VerificationTokenMinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100, unique=True)),
                ('address', models.CharField(db_index=True, max_length=100, unique=True)),
                ('token_address', models.CharField(db_index=True, max_length=100, unique=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minter', to='paytacapos.Merchant')),
            ],
            options={
                'ordering': ('merchant__name',),
            },
        ),
    ]
