# Generated by Django 3.0.14 on 2024-09-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0012_auto_20240906_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
