# Generated by Django 3.0.14 on 2022-12-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0004_auto_20221129_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlinkDeviceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.BooleanField(default=False)),
                ('signature', models.TextField(help_text='Signed data of link_code')),
                ('nonce', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_device_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unlink_request', to='paytacapos.LinkedDeviceInfo')),
            ],
        ),
    ]
