# Generated by Django 3.0.14 on 2023-04-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0005_unlinkdevicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
