# Generated by Django 3.0.14 on 2023-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0006_auto_20230403_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='gmap_business_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
