# Generated by Django 3.0.14 on 2023-07-19 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0007_merchant_gmap_business_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posdevice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='paytacapos.Branch'),
        ),
    ]
