# Generated by Django 3.0.14 on 2023-07-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0007_merchant_gmap_business_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
