# Generated by Django 3.0.14 on 2023-08-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0008_auto_20230719_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='signer_wallet_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
