# Generated by Django 3.0.14 on 2023-08-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0009_merchant_signer_wallet_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='receiving_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='receiving_pubkey',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='receiving_pubkey_hash',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='signer_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='signer_pubkey',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='signer_pubkey_hash',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
