# Generated by Django 3.0.14 on 2023-08-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0010_auto_20230815_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='receiving_pubkey',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='receiving_pubkey_hash',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='signer_pubkey',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='signer_pubkey_hash',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
