# Generated by Django 3.0.14 on 2023-09-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0011_auto_20230824_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='receiving_address',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='receiving_pubkey_hash',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='signer_address',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='signer_pubkey_hash',
        ),
    ]
