# Generated by Django 3.0.14 on 2023-09-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0013_remove_merchant_signer_wallet_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
