# Generated by Django 3.0.14 on 2024-02-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0015_auto_20230906_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='signer_pubkey',
        ),
    ]
