# Generated by Django 3.0.14 on 2024-02-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0016_remove_merchant_signer_pubkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='logo_120',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_logos'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='logo_30',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_logos'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='logo_60',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_logos'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='logo_90',
            field=models.ImageField(blank=True, null=True, upload_to='merchant_logos'),
        ),
    ]
