# Generated by Django 3.0.14 on 2024-02-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0019_auto_20240215_0612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={'ordering': ('name',)},
        ),
    ]
