# Generated by Django 3.0.14 on 2024-06-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0021_auto_20240525_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
