# Generated by Django 3.0.14 on 2024-07-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0024_multiple_merchants_20240704_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='receiving_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
