# Generated by Django 3.0.14 on 2024-08-08 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0026_auto_20240806_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('receiving_address', models.CharField(db_index=True, max_length=75)),
                ('paid', models.BooleanField(default=False)),
                ('pos_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='paytacapos.PosDevice')),
            ],
        ),
    ]
