# Generated by Django 3.0.14 on 2024-08-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0027_pospaymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posdevice',
            name='vault_pubkey',
        ),
    ]
