# Generated by Django 3.0.14 on 2024-09-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0028_remove_posdevice_vault_pubkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='pubkey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='verification_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
