# Generated by Django 3.0.14 on 2024-10-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0030_remove_merchant_verification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PosPaymentRequest',
        ),
    ]
