# Generated by Django 3.0.14 on 2024-10-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0031_auto_20241010_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='index',
            field=models.IntegerField(default=-1),
        ),
    ]
