# Generated by Django 3.0.14 on 2024-10-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0032_auto_20241022_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
