# Generated by Django 3.0.14 on 2025-01-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_cashnonfungibletoken_fixed_supply'),
        ('paytacapos', '0033_auto_20241022_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdevice',
            name='latest_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='main.Transaction'),
        ),
    ]
