# Generated by Django 3.0.14 on 2025-01-14 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0227_merge_20241218_0225'),
        ('main', '0097_merge_20241203_0838'),
        ('paytacapos', '0033_auto_20241022_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOutOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashOutPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytacapos.Merchant')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rampp2p.PaymentType')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytacapos.CashOutOrder')),
            ],
        ),
        migrations.CreateModel(
            name='CashOutPaymentMethodFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('field_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rampp2p.PaymentTypeField')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytacapos.CashOutPaymentMethod')),
            ],
        ),
        migrations.AddField(
            model_name='cashoutorder',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paytacapos.CashOutPaymentMethod'),
        ),
        migrations.AddField(
            model_name='cashoutorder',
            name='transactions',
            field=models.ManyToManyField(to='main.WalletHistory'),
        ),
    ]
