# Generated by Django 3.0.14 on 2025-01-15 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0229_featurecontrol'),
        ('main', '0098_appcontrol'),
        ('paytacapos', '0033_auto_20241022_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytacapos.Merchant')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_payment_methods', to='rampp2p.PaymentType')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('field_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rampp2p.PaymentTypeField')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytacapos.PaymentMethod')),
            ],
        ),
        migrations.CreateModel(
            name='CashOutOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paytacapos.Merchant')),
                ('transactions', models.ManyToManyField(to='main.WalletHistory')),
            ],
        ),
    ]
