# Generated by Django 3.0.14 on 2025-01-14 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0227_merge_20241218_0225'),
        ('paytacapos', '0034_auto_20250114_0332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashOutPaymentMethodFields',
            new_name='CashOutPaymentMethodField',
        ),
    ]
