# Generated by Django 3.0.14 on 2025-01-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0034_posdevice_latest_transaction'),
        ('paytacapos', '0034_cashoutorder_cashouttransaction_paymentmethod_paymentmethodfield'),
    ]

    operations = [
    ]
