# Generated by Django 3.0.14 on 2025-01-31 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_cashnonfungibletoken_fixed_supply'),
        ('paytacapos', '0035_merge_20250127_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashouttransaction',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.Transaction'),
        ),
        migrations.AlterField(
            model_name='cashouttransaction',
            name='wallet_history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.WalletHistory'),
        ),
    ]
