# Generated by Django 3.0.14 on 2025-01-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0227_merge_20241218_0225'),
        ('paytacapos', '0035_auto_20250114_0338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashOutPaymentMethod',
            new_name='MerchantPaymentMethod',
        ),
        migrations.RenameModel(
            old_name='CashOutPaymentMethodField',
            new_name='MerchantPaymentMethodField',
        ),
        migrations.AddField(
            model_name='cashoutorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=50),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
