# Generated by Django 3.0.14 on 2025-01-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0230_auto_20250120_0301'),
        ('paytacapos', '0036_auto_20250131_0346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('payment_type', 'merchant')},
        ),
    ]
