# Generated by Django 3.0.14 on 2025-02-06 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0230_auto_20250120_0301'),
        ('main', '0099_cashnonfungibletoken_fixed_supply'),
        ('paytacapos', '0038_cashoutorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Wallet'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('payment_type', 'wallet')},
        ),
    ]
