# Generated by Django 3.0.14 on 2025-02-06 01:54

from django.db import migrations
import logging
logger = logging.getLogger(__name__)

def init_payment_method_wallet(apps, schema_editor):
    # Initialize payment methods with null wallet field
    PaymentMethod = apps.get_model('paytacapos', 'PaymentMethod')
    Wallet = apps.get_model('main', 'Wallet')

    payment_methods = PaymentMethod.objects.filter(wallet__isnull=True)
    logger.warning(f'Initializing {payment_methods.count()} payment_methods')
    
    for payment_method in payment_methods:
        wallet = Wallet.objects.filter(wallet_hash=payment_method.merchant.wallet_hash)
        if not wallet.exists():
            continue

        payment_method.wallet = wallet.first()
        payment_method.save()

class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0039_auto_20250206_0153'),
    ]

    operations = [
        migrations.RunPython(init_payment_method_wallet)
    ]
