# Generated by Django 3.0.14 on 2025-02-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0040_init_payment_method_wallet_20250206_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='merchant',
        ),
    ]
