# Generated by Django 3.0.14 on 2025-02-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0041_remove_paymentmethod_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
