# Generated by Django 3.0.14 on 2025-02-20 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0042_payoutaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payoutaddress',
            options={'verbose_name': 'Payout Address', 'verbose_name_plural': 'Payout Address'},
        ),
    ]
