# Generated by Django 3.0.14 on 2025-02-25 07:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0044_cashoutorder_payout_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashoutorder',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='cashoutorder',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddField(
            model_name='cashoutorder',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cashoutorder',
            name='payout_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
