# Generated by Django 3.0.14 on 2025-02-25 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0045_auto_20250225_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payoutaddress',
            options={},
        ),
        migrations.AddField(
            model_name='payoutaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payoutaddress',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
