# Generated by Django 3.0.14 on 2025-02-27 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_cashnonfungibletoken_fixed_supply'),
        ('paytacapos', '0046_auto_20250225_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutorder',
            name='payment_method',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paytacapos.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='cashoutorder',
            name='wallet',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.Wallet'),
        ),
    ]
