# Generated by Django 3.0.14 on 2025-02-27 05:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0047_auto_20250227_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoutorder',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cashoutorder',
            name='processed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cashoutorder',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cashoutorder',
            name='payout_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True),
        ),
    ]
