# Generated by Django 3.0.14 on 2025-02-27 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rampp2p', '0230_auto_20250120_0301'),
        ('paytacapos', '0048_auto_20250227_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutorder',
            name='currency',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='cashout_orders', to='rampp2p.FiatCurrency'),
        ),
        migrations.AlterField(
            model_name='cashoutorder',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18),
        ),
    ]
