# Generated by Django 3.0.14 on 2025-03-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0049_auto_20250227_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutaddress',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
