# Generated by Django 3.0.14 on 2025-03-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_cashnonfungibletoken_fixed_supply'),
        ('paytacapos', '0050_auto_20250303_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashouttransaction',
            name='wallet_history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.WalletHistory'),
        ),
    ]
