# Generated by Django 3.0.14 on 2025-03-11 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0051_auto_20250303_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoutorder',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paytacapos.Merchant'),
        ),
    ]
