# Generated by Django 3.0.14 on 2025-03-12 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0052_cashoutorder_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutaddress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paytacapos.CashOutOrder'),
        ),
    ]
