# Generated by Django 3.0.14 on 2025-03-12 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0053_payoutaddress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashoutorder',
            name='payout_address',
        ),
        migrations.AlterField(
            model_name='payoutaddress',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_address', to='paytacapos.CashOutOrder'),
        ),
    ]
