# Generated by Django 3.0.14 on 2025-03-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_cashnonfungibletoken_fixed_supply'),
        ('paytacapos', '0054_auto_20250312_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoutorder',
            name='sats_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cashouttransaction',
            name='txid',
            field=models.CharField(db_index=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='cashouttransaction',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Transaction'),
        ),
    ]
