# Generated by Django 3.0.14 on 2025-03-17 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0055_auto_20250314_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payoutaddress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_address', to='paytacapos.CashOutOrder'),
        ),
    ]
