# Generated by Django 3.0.14 on 2025-03-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0056_auto_20250317_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashouttransaction',
            name='record_type',
            field=models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], db_index=True, max_length=10, null=True),
        ),
    ]
