# Generated by Django 3.0.14 on 2025-03-26 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_auto_20250324_0655'),
        ('paytacapos', '0061_auto_20250326_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posdevice',
            name='latest_transaction',
        ),
        migrations.AddField(
            model_name='posdevice',
            name='latest_history_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='main.WalletHistory'),
        ),
    ]
