# Generated by Django 3.0.14 on 2025-03-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_auto_20250324_0655'),
        ('rampp2p', '0230_auto_20250120_0301'),
        ('paytacapos', '0062_auto_20250326_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOutPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cashoutorder',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='paymentmethodfield',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='paytacapos.PaymentMethod'),
        ),
        migrations.CreateModel(
            name='CashOutPaymentMethodField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('field_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rampp2p.PaymentTypeField')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='paytacapos.CashOutPaymentMethod')),
            ],
        ),
        migrations.AddField(
            model_name='cashoutpaymentmethod',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paytacapos.CashOutOrder'),
        ),
        migrations.AddField(
            model_name='cashoutpaymentmethod',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashout_payment_methods', to='rampp2p.PaymentType'),
        ),
        migrations.AddField(
            model_name='cashoutpaymentmethod',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashout_payment_methods', to='paytacapos.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='cashoutpaymentmethod',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Wallet'),
        ),
    ]
