# Generated by Django 3.0.14 on 2025-03-28 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0063_auto_20250328_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutpaymentmethod',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='paytacapos.CashOutOrder'),
        ),
    ]
