# Generated by Django 3.0.14 on 2025-08-13 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_auto_20250324_0655'),
        ('paytacapos', '0064_auto_20250328_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosWalletHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posid', models.IntegerField(db_index=True)),
                ('wallet_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_wallet_history', to='main.WalletHistory')),
            ],
        ),
    ]
