# Generated by Django 3.0.14 on 2026-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0066_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdevice',
            name='nfc_payments_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
