# Generated by Django 3.0.14 on 2026-05-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytacapos', '0067_posdevice_nfc_payments_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='nfc_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
