# Generated by Django 3.0.14 on 2024-10-11 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paytacapos', '0031_auto_20241010_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pubkey', models.CharField(db_index=True, max_length=75)),
                ('address', models.CharField(db_index=True, max_length=75, unique=True)),
                ('token_address', models.CharField(db_index=True, max_length=75, unique=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaults', to='paytacapos.Merchant')),
            ],
            options={
                'ordering': ('merchant__name',),
            },
        ),
    ]
